"use strict";
/* ============================================================
   FUTBOLINI · data-tuits.js  (7.10 · voz de las redes 2026, de Grok)
   Expansión masiva de TUITS_MOMENTO: jerga chilena real de X/Twitter
   futbolero, memes y wordplay. Tokens {GOLEADOR}/{FIGURA}/{CAPITAN}/
   {ARQUERO}/{DT} se reemplazan por nombres reales del plantel.
   Se auto-mergea en TUITS_MOMENTO (data-voz.js) al cargar.
   NOTA: los contextos empate_pobre / gol_anulado_var / autogol / invicto
   quedan listos; falta engancharlos en ctxDeEvento para que disparen.
   ============================================================ */
const TUITS_EXTRA = [
  { ctx:"gana_agonico", quien:"@barra_del_sur", txt:"90+7 y {GOLEADOR} aparece wn. ME CAGO. ME CAGO VIVO." },
  { ctx:"gana_agonico", quien:"@doña_del_canal13", txt:"ay hijito casi me da un ataque. pero ganamos po. gracias diosito" },
  { ctx:"gana_agonico", quien:"@garrafal_cl", txt:"el rival se estaba sacando la foto del empate. ksksksks" },
  { ctx:"gana_agonico", quien:"@pibe_popular23", txt:"en el último minuto wn yo ya estaba buscando el cuchillo en la cocina" },
  { ctx:"gana_agonico", quien:"@datofutbol_cl", txt:"gol 90+6. primer tanto después de los 90 de {GOLEADOR} en el año. dato." },
  { ctx:"gana_agonico", quien:"@hincha_rival_xd", txt:"no puede ser. no puede ser. esto es un crimen." },
  { ctx:"gana_agonico", quien:"@futbolmemes_chile", txt:"el dt rival viendo el reloj: ya po termina. el reloj: y si no" },
  { ctx:"gana_agonico", quien:"@el_verdadero_hincha", txt:"si esto no te pone la piel de gallina andai en el club equivocado" },
  { ctx:"gana_agonico", quien:"@RadioGolAM", txt:"gol agónico. {GOLEADOR} define abajo. el estadio se cae." },
  { ctx:"gana_agonico", quien:"@cuenta_troll", txt:"el 1 se tiró al lado contrario y la pelota igual le pegó en la cola. SKSKS" },
  { ctx:"gana_agonico", quien:"@tia_del_whatsapp", txt:"ganamos hijos. avísenle al tío que está en la feria" },
  { ctx:"gana_agonico", quien:"@memesdebarra", txt:"yo a los 88: esto ya fue. yo a los 90+7: SOY INMORTAL" },
  { ctx:"gana_agonico", quien:"@hincha_del_fondo", txt:"{FIGURA} corrió como si le debieran la pensión alimenticia. 🐐" },
  { ctx:"gana_agonico", quien:"@DeporteTotal", txt:"tres puntos que valen oro. el camarín lo sabe." },
  { ctx:"gana_agonico", quien:"@weon_del_metro", txt:"me paré en el bus a gritar. la tía me miró como si estuviera loco. lo estoy." },

  { ctx:"pierde_local", quien:"@el_verdadero_hincha", txt:"en casa. con gente. y igual se nos ríen. identidad pura." },
  { ctx:"pierde_local", quien:"@doña_del_canal13", txt:"qué vergüenza hijitos. ni pa la once quedé con ánimo" },
  { ctx:"pierde_local", quien:"@garrafal_cl", txt:"el local juega con 12 (el público) y igual pierde. talento." },
  { ctx:"pierde_local", quien:"@pibe_popular23", txt:"la wea penca. salí antes pa no escuchar los cánticos de ellos" },
  { ctx:"pierde_local", quien:"@hincha_rival_xd", txt:"vengo de visita y me voy con los 3. gracias por la casa wns" },
  { ctx:"pierde_local", quien:"@datofutbol_cl", txt:"0-1 en casa. 4ta derrota local del semestre. duele el excel." },
  { ctx:"pierde_local", quien:"@cuenta_troll", txt:"el estadio más lindo de chile y el fútbol más feo. coherencia." },
  { ctx:"pierde_local", quien:"@futbolmemes_chile", txt:"el himno al inicio: 🔥 el himno al final: funeral con bandas" },
  { ctx:"pierde_local", quien:"@RadioGolAM", txt:"derrota local que deja preguntas. muchas." },
  { ctx:"pierde_local", quien:"@tia_del_whatsapp", txt:"mejor ni hablen en la mesa. dejen al papá tranquilo" },
  { ctx:"pierde_local", quien:"@memesdebarra", txt:"pagamos la entrada pa que nos hagan esto. somos clientes frecuentes del dolor" },
  { ctx:"pierde_local", quien:"@weon_del_metro", txt:"el conductor del 210 me preguntó cómo nos fue. le mentí." },
  { ctx:"pierde_local", quien:"@hincha_del_fondo", txt:"esto no es un mal día. esto ya es identidad. otra vez." },
  { ctx:"pierde_local", quien:"@DeporteTotal", txt:"el local no encontró profundidad. el visitante sí encontró red." },
  { ctx:"pierde_local", quien:"@barra_del_sur", txt:"se nos rieron EN LA CASA wn. EN LA CASA." },

  { ctx:"expulsion", quien:"@pibe_popular23", txt:"la roja más justa del año. se la buscó solito el wn" },
  { ctx:"expulsion", quien:"@garrafal_cl", txt:"segunda amarilla por hablarle al juez. el pico de inteligencia" },
  { ctx:"expulsion", quien:"@doña_del_canal13", txt:"ese cabro no tiene respeto. lo echaron y bien hecho" },
  { ctx:"expulsion", quien:"@cuenta_troll", txt:"se fue expulsado y igual salió aplaudiendo. narcisismo nivel dios" },
  { ctx:"expulsion", quien:"@hincha_rival_xd", txt:"gracias crack. nos dejaste en 11 vs 10. te debemos un asado" },
  { ctx:"expulsion", quien:"@datofutbol_cl", txt:"roja a los 34. el equipo jugó 56 minutos con 10. se notó." },
  { ctx:"expulsion", quien:"@futbolmemes_chile", txt:"el juez: te vas. él: pero si yo. el juez: te vas más." },
  { ctx:"expulsion", quien:"@RadioGolAM", txt:"expulsión que cambia el partido. {CAPITAN} no pudo contenerlo." },
  { ctx:"expulsion", quien:"@el_verdadero_hincha", txt:"la wea de siempre. nos expulsan al único que corría" },
  { ctx:"expulsion", quien:"@memesdebarra", txt:"tarjeta roja speedrun any%" },
  { ctx:"expulsion", quien:"@tia_del_whatsapp", txt:"ese niño necesita una cachetada de la mamá no de un árbitro" },
  { ctx:"expulsion", quien:"@hincha_del_fondo", txt:"se fue y nos dejó botados. clásico." },
  { ctx:"expulsion", quien:"@weon_del_metro", txt:"la roja más anunciada desde que mi tío dijo \"última copa\"" },
  { ctx:"expulsion", quien:"@DeporteTotal", txt:"inconducta. el VAR no salvó a nadie esta vez." },
  { ctx:"expulsion", quien:"@barra_del_sur", txt:"WN SE FUE. SE FUE EL WEON. #FueraElLoco" },

  { ctx:"hat_trick", quien:"@barra_del_sur", txt:"{GOLEADOR} HAT TRICK WN. ANDATE A EUROPA YA." },
  { ctx:"hat_trick", quien:"@garrafal_cl", txt:"tres goles y el tercero de taco. el wn se aburrió de ser humano" },
  { ctx:"hat_trick", quien:"@doña_del_canal13", txt:"ese cabro es un amor. tres goles y saluda a la cámara. qué fino" },
  { ctx:"hat_trick", quien:"@pibe_popular23", txt:"{GOLEADOR} hoy no es de este planeta. 🐐🐐🐐" },
  { ctx:"hat_trick", quien:"@datofutbol_cl", txt:"hat-trick de {GOLEADOR}. 3 goles, 1 asistencia, 8 disparos. bestia." },
  { ctx:"hat_trick", quien:"@hincha_rival_xd", txt:"basta. paren a ese wn. es ilegal lo que está haciendo" },
  { ctx:"hat_trick", quien:"@futbolmemes_chile", txt:"el arquero rival ya pidió cambio de carrera. quiere ser juggler" },
  { ctx:"hat_trick", quien:"@cuenta_troll", txt:"el tercero lo pateó con el alma. y un poco con la cara. ksks" },
  { ctx:"hat_trick", quien:"@RadioGolAM", txt:"hat trick. noche histórica de {GOLEADOR}." },
  { ctx:"hat_trick", quien:"@memesdebarra", txt:"hat trick + bailecito = denuncia en carabineros por abuso de poder" },
  { ctx:"hat_trick", quien:"@el_verdadero_hincha", txt:"pagaría el abono solo pa ver a este wn. el resto es relleno" },
  { ctx:"hat_trick", quien:"@tia_del_whatsapp", txt:"dile a {GOLEADOR} que venga a la casa que le hago cazuela" },
  { ctx:"hat_trick", quien:"@weon_del_metro", txt:"tres goles y yo sin ni una en el fantasy. la vida es cruel" },
  { ctx:"hat_trick", quien:"@DeporteTotal", txt:"el 9 se destapó. tres tantos. cifra de goleador." },
  { ctx:"hat_trick", quien:"@hincha_del_fondo", txt:"{GOLEADOR} es de otro planeta wn 🐐" },

  { ctx:"penal_errado", quien:"@cuenta_troll", txt:"lo tiró tan al medio que el arquero tuvo tiempo de tomarse un café. SKKSKDKD" },
  { ctx:"penal_errado", quien:"@garrafal_cl", txt:"penal errado con estilo. el estilo de no querer ganar" },
  { ctx:"penal_errado", quien:"@pibe_popular23", txt:"se la mandó a la luna wn. a la LUNA." },
  { ctx:"penal_errado", quien:"@doña_del_canal13", txt:"ay no hijito. se puso nervioso el pobre" },
  { ctx:"penal_errado", quien:"@hincha_rival_xd", txt:"gracias crack. te vamos a hacer un altar" },
  { ctx:"penal_errado", quien:"@datofutbol_cl", txt:"penal errado. 3er fallo del semestre desde los 12 pasos." },
  { ctx:"penal_errado", quien:"@futbolmemes_chile", txt:"el 1 ni se tiró. se quedó parado y igual atajó. otra vez." },
  { ctx:"penal_errado", quien:"@el_verdadero_hincha", txt:"si no lo tira {GOLEADOR} no lo tira nadie. y igual lo erró. destino." },
  { ctx:"penal_errado", quien:"@RadioGolAM", txt:"penal desviado. oportunidad clara que se esfuma." },
  { ctx:"penal_errado", quien:"@memesdebarra", txt:"el penal más anunciado desde \"voy a dejar el pisco\"" },
  { ctx:"penal_errado", quien:"@tia_del_whatsapp", txt:"ese niño tiene que ir al psicólogo no al área chica" },
  { ctx:"penal_errado", quien:"@weon_del_metro", txt:"lo soñé anoche. soñé que lo erraba. soy brujo y no quiero" },
  { ctx:"penal_errado", quien:"@hincha_del_fondo", txt:"la wea penca. un penal no se falla hermano" },
  { ctx:"penal_errado", quien:"@DeporteTotal", txt:"el cobrador eligió potencia. le faltó dirección." },
  { ctx:"penal_errado", quien:"@barra_del_sur", txt:"SE LA MANDÓ A LA LUNA WN. ME QUIERO MORIR." },

  { ctx:"goleada_favor", quien:"@barra_del_sur", txt:"4-0 y quiero más. SOY INSUCIABLE." },
  { ctx:"goleada_favor", quien:"@garrafal_cl", txt:"goleada con olor a clasificatoria. el rival ya está en la micro" },
  { ctx:"goleada_favor", quien:"@doña_del_canal13", txt:"qué lindo se ve cuando ganan fácil. hasta el té me sabe mejor" },
  { ctx:"goleada_favor", quien:"@pibe_popular23", txt:"los humillamos wn. #DaleCampeón" },
  { ctx:"goleada_favor", quien:"@hincha_rival_xd", txt:"apaguen las luces. esto ya es abuso" },
  { ctx:"goleada_favor", quien:"@datofutbol_cl", txt:"4-0. 18 remates, 9 al arco. dominio total." },
  { ctx:"goleada_favor", quien:"@futbolmemes_chile", txt:"el dt rival anotando en la pizarra: rezar" },
  { ctx:"goleada_favor", quien:"@cuenta_troll", txt:"el 5to lo anularon por lástima. humanitarios los jueces" },
  { ctx:"goleada_favor", quien:"@RadioGolAM", txt:"goleada que ordena la tabla. {GOLEADOR} con doblete." },
  { ctx:"goleada_favor", quien:"@memesdebarra", txt:"esto no es un partido. es un contenido para tiktok del rival" },
  { ctx:"goleada_favor", quien:"@el_verdadero_hincha", txt:"así se juega en casa. así. copien." },
  { ctx:"goleada_favor", quien:"@tia_del_whatsapp", txt:"manden el resultado al grupo de la familia que están callados" },
  { ctx:"goleada_favor", quien:"@weon_del_metro", txt:"4-0 y el conductor igual me cobró el pasaje. injusticia" },
  { ctx:"goleada_favor", quien:"@DeporteTotal", txt:"contundente. no hay discusión táctica cuando el arco canta así." },
  { ctx:"goleada_favor", quien:"@hincha_del_fondo", txt:"{FIGURA} se paseó. se paseó nomas." },

  { ctx:"remontada", quien:"@barra_del_sur", txt:"íbamos 0-2 y lo dimos vuelta. YO NO TENGO CORAZÓN YA." },
  { ctx:"remontada", quien:"@garrafal_cl", txt:"de la morgue al podio. medicina chilena nivel dios" },
  { ctx:"remontada", quien:"@pibe_popular23", txt:"a los 60 yo ya estaba en la calle. volví corriendo. valió" },
  { ctx:"remontada", quien:"@doña_del_canal13", txt:"nunca pierdan la fe hijitos. nunca." },
  { ctx:"remontada", quien:"@hincha_rival_xd", txt:"cómo se les escapa un 2-0. cómo. explíquenme." },
  { ctx:"remontada", quien:"@datofutbol_cl", txt:"0-2 al 55. 3-2 al 89. remontada estadísticamente rara. ocurrió." },
  { ctx:"remontada", quien:"@futbolmemes_chile", txt:"el dt: cambien la mentalidad. el equipo: ok. *cambia el universo*" },
  { ctx:"remontada", quien:"@cuenta_troll", txt:"el rival celebró el 2-0 como si fuera final. spoiler." },
  { ctx:"remontada", quien:"@RadioGolAM", txt:"remontada heroica. {GOLEADOR} y {FIGURA} autores del milagro." },
  { ctx:"remontada", quien:"@memesdebarra", txt:"script de netflix rechazado por poco creíble. pasó igual." },
  { ctx:"remontada", quien:"@el_verdadero_hincha", txt:"esto es el club. esto. lo otro es turismo." },
  { ctx:"remontada", quien:"@tia_del_whatsapp", txt:"yo a los 2-0 ya estaba planchando. me avisaron. casi me caigo" },
  { ctx:"remontada", quien:"@weon_del_metro", txt:"le grité al chofer 3-2. me bajó dos paraderos antes. justificado" },
  { ctx:"remontada", quien:"@DeporteTotal", txt:"carácter. la palabra de la noche." },
  { ctx:"remontada", quien:"@hincha_del_fondo", txt:"{DT} no se rindió. el plantel tampoco. yo sí a los 60. perdón." },

  { ctx:"clasico_gana", quien:"@barra_del_sur", txt:"CLÁSICO NUESTRO WN. DÍGANLO. DÍGANLO EN VOZ ALTA." },
  { ctx:"clasico_gana", quien:"@garrafal_cl", txt:"les ganamos el clásico y ahora son filósofo en twitter. ksks" },
  { ctx:"clasico_gana", quien:"@pibe_popular23", txt:"el lienzo de ellos quedó pa souvenir. #DaleCampeón" },
  { ctx:"clasico_gana", quien:"@hincha_rival_xd", txt:"..." },
  { ctx:"clasico_gana", quien:"@doña_del_canal13", txt:"qué lindo el clásico cuando gana el mío. el otro día no tanto" },
  { ctx:"clasico_gana", quien:"@datofutbol_cl", txt:"clásico ganado. racha de 3 sin perder el duelo. dato para la mesa." },
  { ctx:"clasico_gana", quien:"@futbolmemes_chile", txt:"ellos: fiesta en casa. nosotros: dj, luces y el último lento" },
  { ctx:"clasico_gana", quien:"@cuenta_troll", txt:"el clásico más lindo es el que se gana. el resto es contenido" },
  { ctx:"clasico_gana", quien:"@RadioGolAM", txt:"el clásico se queda en casa. {FIGURA} fue el diferencial." },
  { ctx:"clasico_gana", quien:"@memesdebarra", txt:"a los rivales les quedó cara de lunes. y es domingo. talentosos" },
  { ctx:"clasico_gana", quien:"@el_verdadero_hincha", txt:"esto no se discute. se canta." },
  { ctx:"clasico_gana", quien:"@tia_del_whatsapp", txt:"el vecino de la u no salió a barrer. coincidencia? no creo" },
  { ctx:"clasico_gana", quien:"@weon_del_metro", txt:"viajo con la camiseta puesta a propósito. que me miren." },
  { ctx:"clasico_gana", quien:"@DeporteTotal", txt:"clásico con identidad. el resultado habla." },
  { ctx:"clasico_gana", quien:"@hincha_del_fondo", txt:"se lo merecían? no. lo ganamos igual. mejor." },

  { ctx:"arquero_figura", quien:"@barra_del_sur", txt:"{ARQUERO} ATAJÓ TODO WN. TODO. ES UN MURO." },
  { ctx:"arquero_figura", quien:"@garrafal_cl", txt:"el 1 rival se fue llorando. el nuestro se fue en hombros" },
  { ctx:"arquero_figura", quien:"@pibe_popular23", txt:"{ARQUERO} hoy no es arquero. es infraestructura" },
  { ctx:"arquero_figura", quien:"@doña_del_canal13", txt:"ese niño del arco es un amor. ataja y saluda. fino" },
  { ctx:"arquero_figura", quien:"@hincha_rival_xd", txt:"cómo ataja tanto ese wn. denúncienlo" },
  { ctx:"arquero_figura", quien:"@datofutbol_cl", txt:"8 atajadas. 2 mano a mano. 1 penal. partido de {ARQUERO}." },
  { ctx:"arquero_figura", quien:"@futbolmemes_chile", txt:"el delantero rival ya le pidió el instagram. pa bloquearlo" },
  { ctx:"arquero_figura", quien:"@cuenta_troll", txt:"atajó una que iba al ángulo con la cara. la cara. ksksks" },
  { ctx:"arquero_figura", quien:"@RadioGolAM", txt:"figura del partido: {ARQUERO}. valla en cero." },
  { ctx:"arquero_figura", quien:"@memesdebarra", txt:"el arco hoy era zona de exclusión aérea" },
  { ctx:"arquero_figura", quien:"@el_verdadero_hincha", txt:"sin {ARQUERO} esto era 4-1 fácil. páguenle más." },
  { ctx:"arquero_figura", quien:"@tia_del_whatsapp", txt:"el portero se merece una empanada del tamaño del estadio" },
  { ctx:"arquero_figura", quien:"@weon_del_metro", txt:"vi 3 atajadas por el celular y casi me bajo en la estación equivocada" },
  { ctx:"arquero_figura", quien:"@DeporteTotal", txt:"seguridad atrás. {ARQUERO} comandó." },
  { ctx:"arquero_figura", quien:"@hincha_del_fondo", txt:"{ARQUERO} te amo. platónico. no me contestes." },

  { ctx:"empate_pobre", quien:"@el_verdadero_hincha", txt:"0-0 que sabe a derrota. agua tibia. nada." },
  { ctx:"empate_pobre", quien:"@garrafal_cl", txt:"empate pobre. el fútbol pidiendo disculpas por existir" },
  { ctx:"empate_pobre", quien:"@pibe_popular23", txt:"pagué entrada pa ver esto. soy un mártir" },
  { ctx:"empate_pobre", quien:"@doña_del_canal13", txt:"qué fome hijito. ni un gol. mejor apago" },
  { ctx:"empate_pobre", quien:"@hincha_rival_xd", txt:"un punto que no le sirve a nadie. empatamos en la miseria" },
  { ctx:"empate_pobre", quien:"@datofutbol_cl", txt:"0-0. 7 remates totales. xG 0.4 vs 0.3. no pasó nada. literal." },
  { ctx:"empate_pobre", quien:"@futbolmemes_chile", txt:"el partido más beige flag del torneo" },
  { ctx:"empate_pobre", quien:"@cuenta_troll", txt:"el único momento de emoción fue cuando se cayó el relator" },
  { ctx:"empate_pobre", quien:"@RadioGolAM", txt:"empate que no deja contento a nadie. juego trabado." },
  { ctx:"empate_pobre", quien:"@memesdebarra", txt:"90 minutos pa terminar igual. el universo tiene humor negro" },
  { ctx:"empate_pobre", quien:"@tia_del_whatsapp", txt:"podían haber venido a tomar once. era lo mismo" },
  { ctx:"empate_pobre", quien:"@weon_del_metro", txt:"el partido y el 210 tienen algo en común: no avanzan" },
  { ctx:"empate_pobre", quien:"@hincha_del_fondo", txt:"la wea penca. un empate así te envejece" },
  { ctx:"empate_pobre", quien:"@DeporteTotal", txt:"poco volumen ofensivo. punto que sabe a poco." },
  { ctx:"empate_pobre", quien:"@barra_del_sur", txt:"ABURRIDO WN. ABURRIDO. ME QUIERO IR A DORMIR." },

  { ctx:"gol_anulado_var", quien:"@barra_del_sur", txt:"EL VAR NOS ROBÓ WN. ROBÓ." },
  { ctx:"gol_anulado_var", quien:"@garrafal_cl", txt:"gol anulado por un offside de la uña del meñique. tecnología de punta" },
  { ctx:"gol_anulado_var", quien:"@pibe_popular23", txt:"ya habíamos celebrado. ya. el var es un psicópata" },
  { ctx:"gol_anulado_var", quien:"@doña_del_canal13", txt:"esa máquina es mala. muy mala. no me gusta" },
  { ctx:"gol_anulado_var", quien:"@hincha_rival_xd", txt:"justicia. aunque duela. ksks no duele" },
  { ctx:"gol_anulado_var", quien:"@datofutbol_cl", txt:"gol anulado VAR. offside milimétrico. el line era correcto." },
  { ctx:"gol_anulado_var", quien:"@futbolmemes_chile", txt:"el var: y si le quitamos la única alegría de la semana" },
  { ctx:"gol_anulado_var", quien:"@cuenta_troll", txt:"anularon el gol y el relator se quedó con la voz en el aire. poesía" },
  { ctx:"gol_anulado_var", quien:"@RadioGolAM", txt:"intervención del VAR. el tanto no sube al marcador." },
  { ctx:"gol_anulado_var", quien:"@memesdebarra", txt:"celebré, me paré, me senté, me paré, me senté. cardio gratis" },
  { ctx:"gol_anulado_var", quien:"@el_verdadero_hincha", txt:"siempre el var contra nosotros. siempre. teoría no tan teoría" },
  { ctx:"gol_anulado_var", quien:"@tia_del_whatsapp", txt:"esa televisión retrasa las cosas pa molestar. apáguenla" },
  { ctx:"gol_anulado_var", quien:"@weon_del_metro", txt:"grité gol en el bus. 20 segundos después el silencio. social death" },
  { ctx:"gol_anulado_var", quien:"@DeporteTotal", txt:"el VAR corrige. duele, pero corrige." },
  { ctx:"gol_anulado_var", quien:"@hincha_del_fondo", txt:"{GOLEADOR} lo hizo todo bien. el software no." },

  { ctx:"autogol", quien:"@cuenta_troll", txt:"se la mandó solo. el 1 ni la vio. SKKSKDKD" },
  { ctx:"autogol", quien:"@garrafal_cl", txt:"autogol de antología. el rival ni pidió el pase" },
  { ctx:"autogol", quien:"@pibe_popular23", txt:"el defensa más goleador del rival. 10/10 colaboración" },
  { ctx:"autogol", quien:"@doña_del_canal13", txt:"ay el pobre. se va a acordar toda la vida" },
  { ctx:"autogol", quien:"@hincha_rival_xd", txt:"gracias crack. te debemos una. de verdad." },
  { ctx:"autogol", quien:"@datofutbol_cl", txt:"autogol 67'. primer tanto en contra del zaguero en 2 años." },
  { ctx:"autogol", quien:"@futbolmemes_chile", txt:"quiso despejar al córner. encontró el ángulo. crack" },
  { ctx:"autogol", quien:"@el_verdadero_hincha", txt:"la wea de siempre. nos hacemos los goles solitos" },
  { ctx:"autogol", quien:"@RadioGolAM", txt:"tanto en contra. el partido se inclina." },
  { ctx:"autogol", quien:"@memesdebarra", txt:"el gol más trabajado del partido y lo hizo el otro equipo. talento" },
  { ctx:"autogol", quien:"@tia_del_whatsapp", txt:"ese niño necesita un abrazo y un cambio de puesto" },
  { ctx:"autogol", quien:"@weon_del_metro", txt:"vi el replay 8 veces. cada vez duele distinto" },
  { ctx:"autogol", quien:"@hincha_del_fondo", txt:"ME QUIERO MORIR. el wn se la clavó solo." },
  { ctx:"autogol", quien:"@DeporteTotal", txt:"error defensivo que termina en red propia." },
  { ctx:"autogol", quien:"@barra_del_sur", txt:"AUTOGOOOOL WN. NO PUEDE SER." },

  { ctx:"invicto", quien:"@barra_del_sur", txt:"invictos wn. INVICTOS. que lo griten en la alameda" }
];
/* auto-merge en el pool del juego */
(function(){ try{ if(typeof TUITS_MOMENTO!=="undefined" && Array.isArray(TUITS_EXTRA)){
  TUITS_EXTRA.forEach(function(t){ TUITS_MOMENTO.push(t); });
} }catch(e){} })();
