"use strict";
/* ============================================================
   FUTBOLINI · idiomas.js  (7.69)
   Sistema de IDIOMA / REGISTRO: Español neutro, Chilensis (de verdad,
   sin voseo argentino), Português. Se llena de a poco.

   Cómo funciona: `T(clave, neutro)` devuelve la frase del idioma activo;
   si esa clave no está traducida, CAE A NEUTRO (nunca queda en blanco).
   Así se puede ir traduciendo pantalla por pantalla sin romper nada.

   Para sumar frases: agregá la `clave` en `FRASES.neutro` (base) y, cuando
   tengas la versión, en `FRASES.cl` (chilensis) y/o `FRASES.pt` (portugués).
   El chilensis lo pule el usuario (voz real); acá va un arranque respetuoso.
   Regla del repo: diversidad sí, burla no.
   ============================================================ */

var IDIOMA="neutro";
var IDIOMAS_DISPONIBLES=[
  ["neutro","🌎 Español neutro"],
  ["cl","🇨🇱 Chilensis"],
  ["pt","🇧🇷 Português"],
  ["en","🇬🇧 English"]
];

var FRASES={
  /* --- BASE: español neutro (sin voseo). Es el fallback de todo. --- */
  neutro:{
    ini_headline:"No manejas un equipo. Manejas una institución.",
    ini_bajada:"Gente con intereses distintos empujando para lados distintos, plata que se acaba, reglas internas que puedes cambiar si tienes el poder para hacerlo, y una historia real que puedes seguir o romper.",
    ini_elige:"1 · Elige club",
    ini_buscar:"Buscar club o ciudad…",
    ini_f_todos:"Todos",
    ini_f_clasicos:"Clásicos '91",
    ini_amigo_tit:"… o juega contra un amigo",
    ini_amigo_txt:"Un duelo dirigido, en vivo, sin cuentas ni servidor: se conectan con un código y cada uno maneja su club.",
    ini_amigo_btn:"🎮 Duelo con un amigo",
    aj_idioma:"Idioma",
    aj_idioma_txt:"Cambia el registro de los textos del juego. El chilensis se va puliendo con el tiempo; lo que aún no esté traducido se muestra en español neutro.",
    esc_atiende:"Atiende antes de avanzar",
    esc_atiende_txt:"Hay cosas que conviene resolver antes de apretar Avanzar. Toca una para ir a resolverla:",
    esc_metas:"Lo que se espera de ti",
    esc_metas_txt:"Metas de la dirigencia para este año. Se evalúan al cierre.",
    esc_como:"Cómo",
    esc_ayudante:"Ayudante",
    esc_ayudante_txt:"Tu mano derecha, gratis y sin servidor. Preguntale de verdad: del rival, la plata, la meta, la copa, la barra.",
    esc_decs:"Decisiones sobre la mesa",
    esc_semana:"Lo que pasó esta semana",
    inst_poder:"Jugadas de poder",
    inst_poder_txt:"No es apretar un botón. Primero tienes que tener al grupo de tu lado y capital. Cada una, una vez por año.",
    inst_grupos:"Grupos de interés",
    merc_obj:"Objetivos en el mercado",
    merc_ces:"Cesiones a préstamo",
    cal_pais:"El país se simula aunque no lo juegues",
    chip_informe:"Informe de la semana",
    chip_rival:"¿Cómo viene el rival?",
    chip_plata:"¿Cómo estamos de plata?",
    chip_camarin:"¿Y el camarín?",
    chip_meta:"¿Qué hago con la meta?",
    chip_domingo:"¿El domingo?",
    chip_vende:"¿Vendemos a alguien?",
    chip_capitan:"¿Hablo con el capitán?",
    chip_directorio:"¿Y el directorio?",
    arco_gol:"⚽ GOL",
    arco_ataja:"🧤 ATAJADA",
    arco_barrera:"🧱 LA BARRERA",
    arco_palo:"🪵 TRAVESAÑO",
    arco_afuera:"↑ AFUERA",
    arco_defensa:"🛡️ DESPEJA",
    arco_hud_pen:"PENAL",
    arco_hud_tl:"TIRO LIBRE",
    arco_hud_cor:"CÓRNER",
    arco_pen_tit:"Penal · dibuja tu tiro",
    arco_tl_tit:"Tiro libre · dibuja tu remate",
    arco_cor_tit:"Córner · dibuja el centro",
    arco_colocado:"Colocado",
    arco_potente:"Potente",
    arco_picadita:"Picadita",
    tanda_tit:"Tanda · dibuja tu penal",
    /* --- escritorio 7.9006 (Claude) --- */
    hist_hoy:"El club hoy",
    esc_once_ver:"Once probable de ",
    scout_rival:"Rival", scout_pos:"Pos", scout_nivel:"Nivel",
    scout_real:"jugador real documentado",
    scout_estim:"Es una lectura estimada: la formación final puede cambiar.",
    scout_niebla:"Ves a los conocidos; el resto es niebla. Un informe de scouting revela el once completo.",
    scout_btn:"Informe completo", scout_sincaja:"No te alcanza la caja para el informe",
    scout_comprado:"Informe comprado",
    dec_urg:"hay que resolverla antes del próximo partido",
    /* ayudante con acciones + metas 7.9006 */
    ay_once:"Armar el once", ay_moral:"Reconquistar el camarín", ay_plantel:"Ver el plantel",
    ay_finanzas:"Ir a Finanzas", ay_inst:"Ir a Institución", ay_metas:"Ver las metas",
    ay_previa:"Ver la previa", ay_mercado:"Ir al Mercado",
    ay_les:"Lesionados", ay_sinles:"No tienes lesionados de peso ahora.",
    ay_nopillo:"No te pillé bien. ¿Es del once, de la plata, de la meta o del rival?",
    ay_c_once:"el once", ay_c_plata:"la plata", ay_c_meta:"la meta", ay_c_rival:"el rival", ay_c_cam:"el camarín", ay_c_les:"los lesionados",
    ay_ph:"Preguntale al ayudante… (rival, once, plata, camarín, meta, mercado…)", ay_preguntar:"Preguntar",
    meta_ir:"Toca para ir a trabajar esta meta", meta_porque:"Por qué importa",
    meta_ok:"Meta cumplida. El directorio la da por buena.", meta_pregunta:"¿Qué hago con la meta",
    dec_elige:"Él elegiría esta", dec_elige_ya:"El ayudante ya marcó su opción", dec_elige_txt:"El ayudante se la jugaría acá. Decides tú.", dec_elige_badge:"él elegiría",
    dec_g_partido:"⚽ Partido", dec_g_plata:"💰 Plata", dec_g_inst:"🏛️ Institución",
    hold_tit:"Partido en pausa",
    hold_txt:"Las decisiones siguen ahí. Vuelve al partido cuando quieras.",
    hold_btn:"Vuelve al partido",
    hold_avanza:"Hay un partido en curso. Vuelve a terminarlo.",
    sim_tit:"Simulando temporadas",
    sim_txt:"El club sigue, no se trabó.",
    sim_prog:"Temporada ",
    sim_de:" de ",
    sim_ok:"No se trabó; el juego sigue.",
    sim_cancel:"Cancelar y volver al año de origen",
    sim_ayuda:"Para probar el juego a fondo: simulo temporadas enteras. Ves el año en pantalla; no se traba. Si cancelas, volvemos al año de origen — la próxima corrida sale distinta.",
    sim_conf5:"Voy a simular 5 temporadas. Vas a ver el progreso; si cancelas, volvemos al año de origen. ¿Seguir?",
    sim_conf40:"Voy a simular hasta 40 temporadas. No se traba. Cancelar te devuelve al año de origen; la próxima corrida no sale igual. ¿Seguir?",
    sim_backhint:"Si cancelas, volvemos al año de origen.",
    sim_back:"Volviste a ",
    sim_back2:". Esta corrida no quedó: la próxima va a ser distinta.",
    cal_prox:"Próximo compromiso",
    cal_ir:"Ir al partido",
    cal_sinprox:"No hay más partidos este año.",
    pla_once:"Once probable",
    pla_form:"Formación",
    pla_pizarra_hint:"La pizarra se arma en la previa del partido.",
    pla_ir_pizarra:"Ir a la previa / pizarra",
    pla_sinpart:"No hay partido para armar la pizarra.",
    merc_siempre:"Puedes firmar todo el año. En enero-febrero y junio-julio llueven ofertas; el resto, el mercado está más quieto.",
    merc_lluvia:"Lluvia de ofertas",
    merc_quieto:"Mercado más quieto",
    merc_obj_lluvia:"Ventana alta: hay más movimiento, cierra ahora si te convence.",
    merc_obj_quieto:"Fuera de la lluvia: menos ofertas, pero igual puedes firmar."
  },
  /* --- CHILENSIS (de verdad): -ai/-ís, 'po', 'cachái', sin voseo argentino. --- */
  cl:{
    ini_headline:"No manejái un equipo, po. Manejái una institución.",
    ini_bajada:"Cabros tirando pa' lados distintos, la plata que no alcanza, reglas internas que podí cambiar si tení el peso pa' hacerlo, y una historia real que podí seguir o mandar a la punta del cerro.",
    ini_elige:"1 · Elegí tu club",
    ini_buscar:"Busca tu club o ciudad…",
    ini_f_todos:"Todos",
    ini_f_clasicos:"Clásicos '91",
    ini_amigo_tit:"… o juega contra un amigo",
    ini_amigo_txt:"Un duelo dirigido, en vivo, sin cuentas ni na': se conectan con un código y cada uno maneja su cuadro.",
    ini_amigo_btn:"🎮 Pícate con un amigo",
    aj_idioma:"Idioma",
    aj_idioma_txt:"Cambia cómo habla el juego. El chilensis se va afinando de a poco; lo que falte sale en neutro por mientras.",
    esc_atiende:"Atiende esto antes de avanzar, po",
    esc_atiende_txt:"Hay weás que conviene resolver antes de apretar Avanzar. Toca una y te digo qué hacer:",
    esc_metas:"Lo que se espera de ti",
    esc_metas_txt:"Las metas de la dirigencia pa este año. Al cierre te las cobran, no te dormái.",
    esc_como:"Cómo se hace",
    esc_ayudante:"Ayudante",
    esc_ayudante_txt:"Tu mano derecha, gratis y sin servidor. Preguntale en serio: del rival, la plata, la meta, la copa, la barra. El weón lee el club de verdad.",
    esc_decs:"Decisiones sobre la mesa",
    esc_semana:"Lo que pasó esta semana",
    inst_poder:"Jugadas de poder",
    inst_poder_txt:"No es apretar un botón y listo. Primero tenís que tener al grupo de tu lado y capital. Cada una, una vez al año. Si no sabís lo que hacís, te explota.",
    inst_grupos:"Grupos de interés",
    merc_obj:"Objetivos en el mercado",
    merc_ces:"Cesiones a préstamo",
    cal_pais:"El país se simula aunque no lo juegues",
    chip_informe:"Informe de la semana",
    chip_rival:"¿Cómo viene el rival?",
    chip_plata:"¿Cómo andamos de luca?",
    chip_camarin:"¿Y el camarín?",
    chip_meta:"¿Qué hago con la meta?",
    chip_domingo:"¿El domingo?",
    chip_vende:"¿Vendemos a alguien?",
    chip_capitan:"¿Hablo con el capitán?",
    chip_directorio:"¿Y el directorio?",
    arco_gol:"⚽ GOL",
    arco_ataja:"🧤 ATAJADA",
    arco_barrera:"🧱 LA BARRERA",
    arco_palo:"🪵 TRAVESAÑO",
    arco_afuera:"↑ AFUERA",
    arco_defensa:"🛡️ DESPEJA",
    arco_hud_pen:"PENAL",
    arco_hud_tl:"TIRO LIBRE",
    arco_hud_cor:"CÓRNER",
    arco_pen_tit:"Penal · dibuja el tiro, po",
    arco_tl_tit:"Tiro libre · dibuja el remate",
    arco_cor_tit:"Córner · dibuja el centro",
    arco_colocado:"Colocado",
    arco_potente:"Potente",
    arco_picadita:"Picadita",
    tanda_tit:"Tanda · dibuja el penal, po",
    hold_tit:"Partido en pausa",
    hold_txt:"Las decisiones siguen ahí, po. Vuelve al partido cuando querái.",
    hold_btn:"Vuelve al partido",
    hold_avanza:"Hay un partido en curso. Vuelve a terminarlo.",
    sim_tit:"Simulando temporadas",
    sim_txt:"El club sigue, no se trabó.",
    sim_prog:"Temporada ",
    sim_de:" de ",
    sim_ok:"No se trabó; el juego sigue.",
    sim_cancel:"Cancelar y volver al año de origen",
    sim_ayuda:"Pa probar el juego a fondo: simulo temporadas enteras. Veí el año en pantalla; no se traba. Si cancelai, volvemos al año de origen — la próxima corrida sale distinta.",
    sim_conf5:"Voy a simular 5 temporadas. Vai a ver el progreso; si cancelai, volvemos al año de origen. ¿Seguimos?",
    sim_conf40:"Voy a simular hasta 40 temporadas. No se traba. Cancelar te devuelve al año de origen; la próxima corrida no sale igual. ¿Seguimos?",
    sim_backhint:"Si cancelai, volvemos al año de origen.",
    sim_back:"Volviste a ",
    sim_back2:". Esta corrida no quedó: la próxima va a ser distinta.",
    cal_prox:"Próximo compromiso",
    cal_ir:"Ir al partido, po",
    cal_sinprox:"No quedan más partidos este año.",
    pla_once:"Once probable",
    pla_form:"Formación",
    pla_pizarra_hint:"La pizarra la armái en la previa del partido.",
    pla_ir_pizarra:"Ir a la previa / pizarra",
    pla_sinpart:"No hay partido pa' armar la pizarra.",
    merc_siempre:"Podí firmar todo el año, po. En enero-febrero y junio-julio llueven ofertas; el resto el mercado está más quieto.",
    merc_lluvia:"Lluvia de ofertas",
    merc_quieto:"Mercado más quieto",
    merc_obj_lluvia:"Ventana alta: hay más movimiento, cierra ahora si te convence.",
    merc_obj_quieto:"Fuera de la lluvia: menos ofertas, pero igual podí firmar."
  },
  /* --- PORTUGUÊS (arranque; el usuario/Grok lo afinan). --- */
  pt:{
    ini_headline:"Você não dirige um time. Dirige uma instituição.",
    ini_bajada:"Gente puxando para lados diferentes, dinheiro que acaba, regras internas que você pode mudar se tiver poder para isso, e uma história real que dá para seguir ou quebrar.",
    ini_elige:"1 · Escolha o clube",
    ini_buscar:"Buscar clube ou cidade…",
    ini_f_todos:"Todos",
    ini_f_clasicos:"Clássicos '91",
    ini_amigo_tit:"… ou jogue contra um amigo",
    ini_amigo_txt:"Um duelo ao vivo, sem contas nem servidor: conectam-se com um código e cada um comanda seu clube.",
    ini_amigo_btn:"🎮 Duelo com um amigo",
    aj_idioma:"Idioma",
    aj_idioma_txt:"Muda o registro dos textos do jogo. O que ainda não estiver traduzido aparece em espanhol neutro.",
    esc_atiende:"Resolva isto antes de avançar",
    esc_atiende_txt:"Há coisas para resolver antes de apertar Avançar. Toque uma para ir até ela:",
    esc_metas:"O que se espera de você",
    esc_metas_txt:"Metas da diretoria para este ano. Avaliam-se no encerramento.",
    esc_como:"Como",
    esc_ayudante:"Assistente",
    esc_ayudante_txt:"Sua mão direita, de graça e sem servidor. Pergunte de verdade: rival, dinheiro, meta, copa, torcida.",
    esc_decs:"Decisões na mesa",
    esc_semana:"O que aconteceu nesta semana",
    inst_poder:"Jogadas de poder",
    inst_poder_txt:"Não é apertar um botão. Primeiro o grupo tem que estar do seu lado, e você precisa de capital. Cada uma, uma vez por ano.",
    inst_grupos:"Grupos de interesse",
    merc_obj:"Objetivos no mercado",
    merc_ces:"Empréstimos",
    cal_pais:"O país se simula mesmo que você não jogue",
    chip_informe:"Informe da semana",
    chip_rival:"Como vem o rival?",
    chip_plata:"Como está o dinheiro?",
    chip_camarin:"E o vestiário?",
    chip_meta:"O que faço com a meta?",
    chip_domingo:"E no domingo?",
    chip_vende:"Vendemos alguém?",
    chip_capitan:"Falo com o capitão?",
    chip_directorio:"E a diretoria?",
    arco_gol:"⚽ GOL",
    arco_ataja:"🧤 DEFESA",
    arco_barrera:"🧱 A BARREIRA",
    arco_palo:"🪵 TRAVE",
    arco_afuera:"↑ PRA FORA",
    arco_defensa:"🛡️ AFASTA",
    arco_hud_pen:"PÊNALTI",
    arco_hud_tl:"FALTA",
    arco_hud_cor:"ESCANTEIO",
    arco_pen_tit:"Pênalti · desenhe o chute",
    arco_tl_tit:"Falta · desenhe o chute",
    arco_cor_tit:"Escanteio · desenhe o cruzamento",
    arco_colocado:"Colocado",
    arco_potente:"Forte",
    arco_picadita:"Cavadinha",
    tanda_tit:"Disputa de pênaltis · desenhe o chute",
    hist_hoy:"O clube hoje",
    esc_once_ver:"Provável escalação de ",
    scout_rival:"Rival", scout_pos:"Pos", scout_nivel:"Nível",
    scout_real:"jogador real documentado",
    scout_estim:"É uma leitura estimada: a escalação final pode mudar.",
    scout_niebla:"Você vê os conhecidos; o resto é névoa. Um relatório revela o XI completo.",
    scout_btn:"Relatório completo", scout_sincaja:"O caixa não cobre o relatório",
    scout_comprado:"Relatório comprado",
    dec_urg:"tem que ser resolvida antes da próxima partida",
    ay_once:"Montar a escalação", ay_moral:"Reconquistar o vestiário", ay_plantel:"Ver o elenco",
    ay_finanzas:"Ir a Finanças", ay_inst:"Ir à Diretoria", ay_metas:"Ver as metas",
    ay_previa:"Ver a prévia", ay_mercado:"Ir ao Mercado",
    ay_les:"Lesionados", ay_sinles:"Sem lesionados de peso agora.",
    ay_nopillo:"Não peguei bem. É da escalação, do dinheiro, da meta ou do rival?",
    ay_c_once:"a escalação", ay_c_plata:"o dinheiro", ay_c_meta:"a meta", ay_c_rival:"o rival", ay_c_cam:"o vestiário", ay_c_les:"os lesionados",
    ay_ph:"Pergunte ao auxiliar… (rival, escalação, dinheiro, elenco, meta, mercado…)", ay_preguntar:"Perguntar",
    meta_ir:"Toque para trabalhar esta meta", meta_porque:"Por que importa",
    meta_ok:"Meta cumprida. A diretoria aprova.", meta_pregunta:"O que faço com a meta",
    dec_elige:"Ele escolheria esta", dec_elige_ya:"O auxiliar já marcou a escolha", dec_elige_txt:"O auxiliar se arriscaria aqui. Você decide.", dec_elige_badge:"escolha dele",
    dec_g_partido:"⚽ Partida", dec_g_plata:"💰 Dinheiro", dec_g_inst:"🏛️ Diretoria",
    hold_tit:"Partida em pausa",
    hold_txt:"As decisões continuam aí. Volte ao jogo quando quiser.",
    hold_btn:"Voltar à partida",
    hold_avanza:"Há uma partida em curso. Volte para terminá-la.",
    sim_tit:"Simulando temporadas",
    sim_txt:"O clube segue, não travou.",
    sim_prog:"Temporada ",
    sim_de:" de ",
    sim_ok:"Não travou; o jogo segue.",
    sim_cancel:"Cancelar e voltar ao ano de origem",
    sim_ayuda:"Para testar o jogo: simulo temporadas inteiras. Você vê o ano na tela; não trava. Se cancelar, voltamos ao ano de origem — a próxima corrida sai diferente.",
    sim_conf5:"Vou simular 5 temporadas. Você vê o progresso; se cancelar, voltamos ao ano de origem. Seguir?",
    sim_conf40:"Vou simular até 40 temporadas. Não trava. Cancelar te devolve ao ano de origem; a próxima corrida não sai igual. Seguir?",
    sim_backhint:"Se cancelar, voltamos ao ano de origem.",
    sim_back:"Você voltou a ",
    sim_back2:". Esta corrida não ficou: a próxima vai ser diferente.",
    cal_prox:"Próximo compromisso",
    cal_ir:"Ir à partida",
    cal_sinprox:"Não há mais partidas este ano.",
    pla_once:"Onze provável",
    pla_form:"Formação",
    pla_pizarra_hint:"O quadro tático se arma na prévia da partida.",
    pla_ir_pizarra:"Ir à prévia / quadro",
    pla_sinpart:"Não há partida para armar o quadro.",
    merc_siempre:"Você pode assinar o ano inteiro. Em janeiro-fevereiro e junho-julho chovem ofertas; no resto o mercado fica mais quieto.",
    merc_lluvia:"Chuva de ofertas",
    merc_quieto:"Mercado mais quieto",
    merc_obj_lluvia:"Janela alta: tem mais movimento, feche agora se convencer.",
    merc_obj_quieto:"Fora da chuva: menos ofertas, mas você ainda pode assinar."
  },
  en:{
    ini_headline:"You don't run a team. You run an institution.",
    ini_bajada:"People pulling in different directions, money that runs out, house rules you can change if you have the power, and a real history you can follow or break.",
    ini_elige:"1 · Pick a club",
    ini_buscar:"Search club or city…",
    ini_f_todos:"All",
    ini_f_clasicos:"'91 classics",
    ini_amigo_tit:"… or play a friend",
    ini_amigo_txt:"A live directed duel, no accounts, no server: you connect with a code and each of you runs a club.",
    ini_amigo_btn:"🎮 Duel a friend",
    aj_idioma:"Language",
    aj_idioma_txt:"Changes the game's voice. Anything not translated yet falls back to neutral Spanish.",
    esc_atiende:"Handle this before you advance",
    esc_atiende_txt:"There are things to settle before you hit Advance. Tap one to go deal with it:",
    esc_metas:"What they expect of you",
    esc_metas_txt:"The board's targets for this year. They get scored at the close.",
    esc_como:"How",
    esc_ayudante:"Assistant",
    esc_ayudante_txt:"Your right hand, free, no server. Ask for real: the rival, the money, the target, the cup, the barra.",
    esc_decs:"Decisions on the table",
    esc_semana:"What happened this week",
    inst_poder:"Power plays",
    inst_poder_txt:"It is not a button. First you need the group on your side, and capital. Each one, once a year.",
    inst_grupos:"Interest groups",
    merc_obj:"Market objectives",
    merc_ces:"Loans",
    cal_pais:"The country simulates even if you don't play it",
    chip_informe:"Week report",
    chip_rival:"How's the rival looking?",
    chip_plata:"How's the money?",
    chip_camarin:"And the dressing room?",
    chip_meta:"What do I do with the target?",
    chip_domingo:"Sunday?",
    chip_vende:"Do we sell someone?",
    chip_capitan:"Do I talk to the captain?",
    chip_directorio:"And the board?",
    arco_gol:"⚽ GOAL",
    arco_ataja:"🧤 SAVED",
    arco_barrera:"🧱 THE WALL",
    arco_palo:"🪵 CROSSBAR",
    arco_afuera:"↑ WIDE",
    arco_defensa:"🛡️ CLEARED",
    arco_hud_pen:"PENALTY",
    arco_hud_tl:"FREE KICK",
    arco_hud_cor:"CORNER",
    arco_pen_tit:"Penalty · draw your shot",
    arco_tl_tit:"Free kick · draw your shot",
    arco_cor_tit:"Corner · draw the cross",
    arco_colocado:"Placed",
    arco_potente:"Power",
    arco_picadita:"Chip",
    tanda_tit:"Shootout · draw your penalty",
    hist_hoy:"The club today",
    esc_once_ver:"Likely XI of ",
    scout_rival:"Rival", scout_pos:"Pos", scout_nivel:"Rating",
    scout_real:"documented real player",
    scout_estim:"It's an estimate: the final lineup may change.",
    scout_niebla:"You see the known faces; the rest is fog. A scouting report reveals the full XI.",
    scout_btn:"Full report", scout_sincaja:"You can't afford the report",
    scout_comprado:"Report bought",
    dec_urg:"must be settled before the next match",
    ay_once:"Set the lineup", ay_moral:"Win back the dressing room", ay_plantel:"See the squad",
    ay_finanzas:"Go to Finance", ay_inst:"Go to Board", ay_metas:"See the targets",
    ay_previa:"See the preview", ay_mercado:"Go to Market",
    ay_les:"Injured", ay_sinles:"No key injuries right now.",
    ay_nopillo:"I didn't get that. Is it about the lineup, money, the target or the rival?",
    ay_c_once:"the lineup", ay_c_plata:"the money", ay_c_meta:"the target", ay_c_rival:"the rival", ay_c_cam:"the dressing room", ay_c_les:"the injured",
    ay_ph:"Ask the assistant… (rival, lineup, money, squad, target, market…)", ay_preguntar:"Ask",
    meta_ir:"Tap to go work on this target", meta_porque:"Why it matters",
    meta_ok:"Target met. The board signs off.", meta_pregunta:"What do I do about the target",
    dec_elige:"He'd pick this one", dec_elige_ya:"The assistant already marked his pick", dec_elige_txt:"The assistant would go for this. Your call.", dec_elige_badge:"his pick",
    dec_g_partido:"⚽ Match", dec_g_plata:"💰 Money", dec_g_inst:"🏛️ Board",
    hold_tit:"Match paused",
    hold_txt:"Your decisions are still there. Come back to the match when you want.",
    hold_btn:"Back to the match",
    hold_avanza:"There's a match in progress. Go finish it.",
    sim_tit:"Simulating seasons",
    sim_txt:"The club is still going. It didn't freeze.",
    sim_prog:"Season ",
    sim_de:" of ",
    sim_ok:"It didn't freeze; the game is running.",
    sim_cancel:"Cancel and go back to the starting year",
    sim_ayuda:"To stress-test the game I simulate full seasons. You see the year on screen; it doesn't freeze. Cancel restores the year you started from — the next run will be different.",
    sim_conf5:"I'll simulate 5 seasons. You'll see progress; cancel restores the starting year. Continue?",
    sim_conf40:"I'll simulate up to 40 seasons. It won't freeze. Cancel restores the starting year; the next run won't play out the same. Continue?",
    sim_backhint:"If you cancel, we go back to the starting year.",
    sim_back:"You're back in ",
    sim_back2:". This run didn't stick: the next one will be different.",
    cal_prox:"Next fixture",
    cal_ir:"Go to the match",
    cal_sinprox:"No more matches this year.",
    pla_once:"Probable XI",
    pla_form:"Formation",
    pla_pizarra_hint:"The tactics board is set in the match preview.",
    pla_ir_pizarra:"Go to preview / board",
    pla_sinpart:"No match to set the board.",
    merc_siempre:"You can sign all year. Offers pour in January–February and June–July; the rest of the year the market is quieter.",
    merc_lluvia:"Offer rush",
    merc_quieto:"Quieter market",
    merc_obj_lluvia:"High window: more movement — close now if it convinces you.",
    merc_obj_quieto:"Off the rush: fewer offers, but you can still sign."
  }
};

/* ---- Pools de tuits POR IDIOMA (se suman a los del pool base según contexto).
   Chilensis crudo de cancha (aparece SOLO en modo Chilensis; neutro/pt quedan limpios).
   Escrito con la voz del usuario. Placeholder {GOLEADOR}. --- */
var _GOL_CL=[
  {quien:"@barra_del_sur", txt:"GOOOOOOOL GOOOOOL CONCHETUMARE, TE AMO {GOLEADOR}, HAZME UN HIJO!!"},
  {quien:"@weon_del_metro", txt:"GOOOOL WN GOOOOL, {GOLEADOR} ERÍS GRANDE, LA CTM QUE TE AMO"},
  {quien:"@hincha_insomne", txt:"AAAAAH GOOOOOL, {GOLEADOR} POR LA CHUCHA QUE JUEGA BIEN, GRÍTALO"},
  {quien:"@pibe_popular23", txt:"SE ROMPIÓ LA RED CTM, {GOLEADOR} ERÍS UN CRACK, TE LLEVO AL ALTAR"},
  {quien:"@dona_del_barrio", txt:"gooool mijito lindo, {GOLEADOR} me lo saludan a la mamá, qué golazo por dios"}
];
var TUITS_IDIOMA={
  cl:{
    gol_propio:_GOL_CL,
    gana_agonico:_GOL_CL.concat([{quien:"@albo_insomne", txt:"EN LA HORA CTM, {GOLEADOR} NOS SALVÓ LA VIDA, LLORO"}]),
    remontada:_GOL_CL.concat([{quien:"@garrafal_cl", txt:"DE LA NADA WN, {GOLEADOR} DIO VUELTA TODO, QUÉ EQUIPO CTM"}]),
    clasico_gana:_GOL_CL.concat([{quien:"@barra_del_sur", txt:"EN EL CLÁSICO CTM, {GOLEADOR} LOS HIZO LLORAR, ESTO NO SE OLVIDA"}]),
    goleada_favor:_GOL_CL,
    hat_trick:[{quien:"@datofutbol_cl", txt:"TRES {GOLEADOR}, TRES CTM. HÁGANLE UNA ESTATUA AL TIRO"}].concat(_GOL_CL)
  }
};

/* Resuelve una clave por el idioma activo, con fallback a neutro y a un default. */
function T(clave, neutro){
  var pack=FRASES[IDIOMA];
  if(pack && pack[clave]!=null) return pack[clave];
  if(FRASES.neutro && FRASES.neutro[clave]!=null) return FRASES.neutro[clave];
  return (neutro!=null)?neutro:clave;
}
/* Cambia el idioma activo (si existe el pack). */
function setIdioma(k){ if(k && (FRASES[k]||k==="neutro")) IDIOMA=k; return IDIOMA; }
function idiomaActual(){ return IDIOMA; }
