"use strict";
/* ============================================================
   FUTBOLINI · idiomas.js  (7.69)
   Sistema de IDIOMA / REGISTRO: Español neutro, Chilensis (de verdad,
   sin voseo argentino), Português. Se llena de a poco.

   Cómo funciona: `T(clave, neutro)` devuelve la frase del idioma activo;
   si esa clave no está traducida, CAE A NEUTRO (nunca queda en blanco).
   Así se puede ir traduciendo pantalla por pantalla sin romper nada.

   Para sumar frases: agregá la `clave` en `FRASES.neutro` (base) y, cuando
   tengas la versión, en `FRASES.cl` (chilensis) y/o `FRASES.pt` (portugués).
   El chilensis lo pule el usuario (voz real); acá va un arranque respetuoso.
   Regla del repo: diversidad sí, burla no.
   ============================================================ */

var IDIOMA="neutro";
var IDIOMAS_DISPONIBLES=[
  ["neutro","🌎 Español neutro"],
  ["cl","🇨🇱 Chilensis"],
  ["pt","🇧🇷 Português"],
  ["en","🇬🇧 English"]
];

var FRASES={
  /* --- BASE: español neutro (sin voseo). Es el fallback de todo. --- */
  neutro:{
    ini_headline:"No manejas un equipo. Manejas una institución.",
    ini_bajada:"Gente con intereses distintos empujando para lados distintos, plata que se acaba, reglas internas que puedes cambiar si tienes el poder para hacerlo, y una historia real que puedes seguir o romper.",
    ini_elige:"1 · Elige club",
    ini_buscar:"Buscar club o ciudad…",
    ini_f_todos:"Todos",
    ini_f_clasicos:"Clásicos '91",
    ini_amigo_tit:"… o juega contra un amigo",
    ini_amigo_txt:"Un duelo dirigido, en vivo, sin cuentas ni servidor: se conectan con un código y cada uno maneja su club.",
    ini_amigo_btn:"🎮 Duelo con un amigo",
    aj_idioma:"Idioma",
    aj_idioma_txt:"Cambia el registro de los textos del juego. El chilensis se va puliendo con el tiempo; lo que aún no esté traducido se muestra en español neutro.",
    aj_nav:"Navegación",
    aj_nav_pc:"En el computador",
    aj_nav_cel:"En el celular",
    aj_nav_cinta:"Cinta (todas las secciones)",
    aj_nav_mas:"Compacto (4 + Más)",
    aj_nav_txt:"Computador: barra a la izquierda (como la Wii) o pestañas arriba. Celular: la cinta de abajo se desliza con el dedo. El modo compacto deja cuatro atajos y un Más. Ajustes siempre está en ⚙️, no en el menú.",
    esc_atiende:"Atiende antes de avanzar",
    esc_atiende_txt:"Hay cosas que conviene resolver antes de apretar Avanzar. Toca una para ir a resolverla:",
    esc_metas:"Lo que se espera de ti",
    esc_metas_txt:"Metas de la dirigencia para este año. Se evalúan al cierre.",
    esc_como:"Cómo",
    esc_ayudante:"Ayudante",
    esc_ayudante_txt:"Tu mano derecha, gratis y sin servidor. Preguntale de verdad: del rival, la plata, la meta, la copa, la barra.",
    esc_decs:"Decisiones sobre la mesa",
    esc_semana:"Lo que pasó esta semana",
    inst_poder:"Jugadas de poder",
    inst_poder_txt:"No es apretar un botón. Primero tienes que tener al grupo de tu lado y capital. Cada una, una vez por año.",
    inst_grupos:"Grupos de interés",
    merc_obj:"Objetivos en el mercado",
    merc_ces:"Cesiones a préstamo",
    cal_pais:"El país se simula aunque no lo juegues",
    chip_informe:"Informe de la semana",
    chip_rival:"¿Cómo viene el rival?",
    chip_plata:"¿Cómo estamos de plata?",
    chip_camarin:"¿Y el camarín?",
    chip_meta:"¿Qué hago con la meta?",
    chip_domingo:"¿El domingo?",
    chip_vende:"¿Vendemos a alguien?",
    chip_capitan:"¿Hablo con el capitán?",
    chip_directorio:"¿Y el directorio?",
    arco_gol:"⚽ GOL",
    arco_ataja:"🧤 ATAJADA",
    arco_barrera:"🧱 LA BARRERA",
    arco_palo:"🪵 TRAVESAÑO",
    arco_palo_in:"⚽ PALO ADENTRO",
    arco_afuera:"↑ AFUERA",
    arco_defensa:"🛡️ DESPEJA",
    arco_hud_pen:"PENAL",
    arco_hud_tl:"TIRO LIBRE",
    arco_hud_cor:"CÓRNER",
    arco_pen_tit:"Penal · dibuja tu tiro",
    arco_tl_tit:"Tiro libre · dibuja tu remate",
    arco_cor_tit:"Córner · dibuja el centro",
    arco_colocado:"Colocado",
    arco_potente:"Potente",
    arco_picadita:"Picadita",
    arco_apunta:"Tocá el arco para apuntar",
    tanda_tit:"Tanda · dibuja tu penal",
    /* --- escritorio 7.9006 (Claude) --- */
    hist_hoy:"El club hoy",
    esc_once_ver:"Once probable de ",
    scout_rival:"Rival", scout_pos:"Pos", scout_nivel:"Nivel",
    scout_real:"jugador real documentado",
    scout_estim:"Es una lectura estimada: la formación final puede cambiar.",
    scout_niebla:"Ves a los conocidos; el resto es niebla. Pide el informe y ves el once completo — no cuesta caja.",
    scout_btn:"Informe completo", scout_sincaja:"No te alcanza la caja para el informe",
    scout_comprado:"Informe listo", scout_listo:"Informe listo", scout_precio:"gratis", scout_gratis:"gratis",
    don_aviso_btn:"Ver un aviso · apoyar sin plata",
    don_aviso_tit:"Seis segundos de tu tiempo",
    don_aviso_txt:"Un día acá puede salir un anuncio. Hoy es una pausa de 6 segundos: el autor no cobra y el juego no se bloquea. Nadie te obliga a apretar.",
    don_aviso_wait:"Espera un momento…",
    don_aviso_ok:"Listo. Gracias por el tiempo.",
    don_aviso_n:"Avisos vistos esta partida",
    don_aviso_hint:"Apoyar gratis: das atención, no plata. Sirve igual.",
    don_aviso_aj:"El aviso gratis (hueco de anuncio) está en Ajustes · ⚙️. Nadie te obliga.",
    dec_urg:"hay que resolverla antes del próximo partido",
    /* ayudante con acciones + metas 7.9006 */
    ay_once:"Armar el once", ay_moral:"Reconquistar el camarín", ay_plantel:"Ver el plantel",
    ay_finanzas:"Ir a Finanzas", ay_inst:"Ir a Institución", ay_metas:"Ver las metas",
    ay_previa:"Ver la previa", ay_mercado:"Ir al Mercado",
    ay_les:"Lesionados", ay_sinles:"No tienes lesionados de peso ahora.",
    ay_nopillo:"No te pillé bien. ¿Es del once, de la plata, de la meta o del rival?",
    ay_c_once:"el once", ay_c_plata:"la plata", ay_c_meta:"la meta", ay_c_rival:"el rival", ay_c_cam:"el camarín", ay_c_les:"los lesionados",
    ay_ph:"Preguntale al ayudante… (rival, once, plata, camarín, meta, mercado…)", ay_preguntar:"Preguntar",
    meta_ir:"Toca para ir a trabajar esta meta", meta_porque:"Por qué importa",
    meta_ok:"Meta cumplida. El directorio la da por buena.", meta_pregunta:"¿Qué hago con la meta",
    dec_elige:"Él elegiría esta", dec_elige_ya:"El ayudante ya marcó su opción", dec_elige_txt:"El ayudante se la jugaría acá. Decides tú.", dec_elige_badge:"él elegiría",
    dec_g_partido:"⚽ Partido", dec_g_plata:"💰 Plata", dec_g_inst:"🏛️ Institución",
    jor_tit:"La fecha se juega", jor_resto:"Mientras tanto, en las otras canchas:",
    mas_cuenta:"Cuenta", mep_solo:"En esta época solo se sigue el torneo local: el resto del continente no está modelado para este año.",
    mep_nacional:"el Nacional",
    riv_racha:"Cómo viene", riv_sin:"Primera vez que se cruzan este año.",
    riv_puesto:"En la tabla va", riv_ult:"La última vez te ganó.", riv_ult_yo:"La última vez le ganaste.",
    riv_ult_e:"La última vez empataron.", riv_nuevo:"Todavía no jugó esta temporada.", riv_otra:"Juega en otro torneo: no comparten tabla.",
    cal_prog:"Temporada", cal_de:"de", cal_sig:"Lo que viene",
    fed_escalera:"Escalera del poder", fed_anfp:"Asociación local", fed_conmebol:"CONMEBOL", fed_fifa:"FIFA",
    fed_falta:"Te faltan jugadas de poder para el próximo escalón",
    fed_ok:"Escalón conquistado", fed_guerra:"Guerra de asociaciones",
    fed_cupos:"Cupos internacionales", fed_robado:"Cupo robado a la vecina",
    fed_sin:"Todavía no diriges la asociación. Gana la elección para abrir la escalera.",
    fed_subiste:"Subiste un escalón en el poder del fútbol",
    jor_saltar:"Saltar a los resultados", jor_tabla:"Cómo quedó la tabla",
    jor_quieta:"La tabla no se movió con esta fecha.", jor_mundo:"Mientras tanto, afuera",
    jor_tabla_ver:"Ver la tabla completa", jor_esc:"Al escritorio",
    jor_panel:"La liga se movió", jor_ver:"Ver cómo se jugó la fecha",
    jor_cal:"Ir al calendario", jor_repetir:"Repetir la fecha",
    sem_tit:"Parte de la semana", sem_caja:"Caja de la semana", sem_otros:"Otros partidos de la fecha",
    av_jugar:"Jugar", av_semana:"Avanzar semana", av_cierre:"Cerrar temporada",
    q92_calma:"Bajar el perfil", q92_confianza:"Salir con confianza", q92_palo:"Un palo y a la cancha",
    q92_humilde:"Bajar el perfil", q92_bancar:"Bancarlo de frente", q92_palo2:"Un palo y a la siguiente",
    mv_tit:"El mundo se movió", mv_nada:"Semana tranquila afuera. Nadie se movió.",
    mv_dt:"Cambio de banca", mv_fichaje:"Se movió el mercado", mv_racha:"Racha", mv_ver:"Ver todo lo que pasó",
    mv_golpe:"Golpe de la fecha",
    hold_tit:"Partido en pausa",
    hold_txt:"Las decisiones siguen ahí. Vuelve al partido cuando quieras.",
    hold_btn:"Vuelve al partido",
    hold_avanza:"Hay un partido en curso. Vuelve a terminarlo.",
    sim_tit:"Simulando temporadas",
    sim_txt:"El club sigue, no se trabó.",
    sim_prog:"Temporada ",
    sim_de:" de ",
    sim_ok:"No se trabó; el juego sigue.",
    sim_cancel:"Cancelar y volver al año de origen",
    sim_ayuda:"Para probar el juego a fondo: simulo temporadas enteras. Ves el año en pantalla; no se traba. Si cancelas, volvemos al año de origen — la próxima corrida sale distinta.",
    sim_conf5:"Voy a simular 5 temporadas. Vas a ver el progreso; si cancelas, volvemos al año de origen. ¿Seguir?",
    sim_conf40:"Voy a simular hasta 40 temporadas. No se traba. Cancelar te devuelve al año de origen; la próxima corrida no sale igual. ¿Seguir?",
    sim_backhint:"Si cancelas, volvemos al año de origen.",
    sim_back:"Volviste a ",
    sim_back2:". Esta corrida no quedó: la próxima va a ser distinta.",
    sim_fecha:"fecha",
    sim_pos:"posición",
    sim_ultcamp:"último campeón",
    sim_campeonar:"campeón",
    cop_viene:"Cruces que vienen en el país",
    cop_resto_grupo:"Resto del grupo",
    cop_sorteo_pendiente:"Los grupos del país ya terminaron su fase. La fase eliminatoria del resto del país no está modelada; seguí las tablas de arriba.",
    cal_prox:"Próximo compromiso",
    cal_ir:"Ir al partido",
    cal_sinprox:"No hay más partidos este año.",
    pla_once:"Once probable",
    pla_form:"Formación",
    pla_pizarra_hint:"La pizarra se arma en la previa del partido.",
    pla_ir_pizarra:"Ir a la previa / pizarra",
    pla_sinpart:"No hay partido para armar la pizarra.",
    merc_siempre:"La ventana abre en enero-febrero y junio-julio. Fuera de eso negocias y dejas el trato hecho.",
    merc_lluvia:"Ventana abierta",
    merc_quieto:"Ventana cerrada",
    merc_ventana:"La ventana abre en enero-febrero y junio-julio. Fuera de eso negocias y dejas el trato hecho; firmas cuando el mercado lo permite.",
    merc_cerrada:"Ventana cerrada · próxima: ",
    merc_pre:"Preacuerdos",
    merc_obj_lluvia:"Ventana abierta: cierra ahora si te convence.",
    merc_obj_quieto:"Ventana cerrada: puedes negociar y dejar el trato hecho.",
    merc_obj_abierta:"Ventana abierta: cierra ahora si te convence. Son jugadores de los otros clubes, no inventados.",
    merc_obj_cerrada:"Ventana cerrada: puedes negociar y dejar el trato hecho."
  },
  /* --- CHILENSIS (de verdad): -ai/-ís, 'po', 'cachái', sin voseo argentino. --- */
  cl:{
    ini_headline:"No manejái un equipo, po. Manejái una institución.",
    ini_bajada:"Cabros tirando pa' lados distintos, la plata que no alcanza, reglas internas que podí cambiar si tení el peso pa' hacerlo, y una historia real que podí seguir o mandar a la punta del cerro.",
    ini_elige:"1 · Elegí tu club",
    ini_buscar:"Busca tu club o ciudad…",
    ini_f_todos:"Todos",
    ini_f_clasicos:"Clásicos '91",
    ini_amigo_tit:"… o juega contra un amigo",
    ini_amigo_txt:"Un duelo dirigido, en vivo, sin cuentas ni na': se conectan con un código y cada uno maneja su cuadro.",
    ini_amigo_btn:"🎮 Pícate con un amigo",
    aj_idioma:"Idioma",
    aj_idioma_txt:"Cambia cómo habla el juego. El chilensis se va afinando de a poco; lo que falte sale en neutro por mientras.",
    aj_nav:"Navegación",
    aj_nav_pc:"En el computador",
    aj_nav_cel:"En el celu",
    aj_nav_cinta:"Cinta (todas las secciones)",
    aj_nav_mas:"Compacto (4 + Más)",
    aj_nav_txt:"En el PC: barra a la izquierda (como la Wii) o pestañas arriba. En el celu: la cinta de abajo se recorre con el dedo. El compacto deja cuatro atajos y un Más. Ajustes siempre está en ⚙️.",
    esc_atiende:"Atiende esto antes de avanzar, po",
    esc_atiende_txt:"Hay weás que conviene resolver antes de apretar Avanzar. Toca una y te digo qué hacer:",
    esc_metas:"Lo que se espera de ti",
    esc_metas_txt:"Las metas de la dirigencia pa este año. Al cierre te las cobran, no te dormái.",
    esc_como:"Cómo se hace",
    esc_ayudante:"Ayudante",
    esc_ayudante_txt:"Tu mano derecha, gratis y sin servidor. Preguntale en serio: del rival, la plata, la meta, la copa, la barra. El weón lee el club de verdad.",
    esc_decs:"Decisiones sobre la mesa",
    esc_semana:"Lo que pasó esta semana",
    inst_poder:"Jugadas de poder",
    inst_poder_txt:"No es apretar un botón y listo. Primero tenís que tener al grupo de tu lado y capital. Cada una, una vez al año. Si no sabís lo que hacís, te explota.",
    inst_grupos:"Grupos de interés",
    merc_obj:"Objetivos en el mercado",
    merc_ces:"Cesiones a préstamo",
    cal_pais:"El país se simula aunque no lo juegues",
    chip_informe:"Informe de la semana",
    chip_rival:"¿Cómo viene el rival?",
    chip_plata:"¿Cómo andamos de luca?",
    chip_camarin:"¿Y el camarín?",
    chip_meta:"¿Qué hago con la meta?",
    chip_domingo:"¿El domingo?",
    chip_vende:"¿Vendemos a alguien?",
    chip_capitan:"¿Hablo con el capitán?",
    chip_directorio:"¿Y el directorio?",
    arco_gol:"⚽ GOL",
    arco_ataja:"🧤 ATAJADA",
    arco_barrera:"🧱 LA BARRERA",
    arco_palo:"🪵 TRAVESAÑO",
    arco_palo_in:"⚽ PALO ADENTRO",
    arco_afuera:"↑ AFUERA",
    arco_defensa:"🛡️ DESPEJA",
    arco_hud_pen:"PENAL",
    arco_hud_tl:"TIRO LIBRE",
    arco_hud_cor:"CÓRNER",
    arco_pen_tit:"Penal · dibuja el tiro, po",
    arco_tl_tit:"Tiro libre · dibuja el remate",
    arco_cor_tit:"Córner · dibuja el centro",
    arco_colocado:"Colocado",
    arco_potente:"Potente",
    arco_picadita:"Picadita",
    arco_apunta:"Tocá el arco para apuntar",
    tanda_tit:"Tanda · dibuja el penal, po",
    hold_tit:"Partido en pausa",
    hold_txt:"Las decisiones siguen ahí, po. Vuelve al partido cuando querái.",
    hold_btn:"Vuelve al partido",
    hold_avanza:"Hay un partido en curso. Vuelve a terminarlo.",
    jor_tit:"La fecha se está jugando", jor_resto:"Mientras tanto, en las otras canchas:",
    mep_solo:"En esta época solo se sigue el torneo local: el resto del continente no está modelado pa este año.",
    mep_nacional:"el Nacional",
    riv_racha:"Cómo viene", riv_sin:"Primera vez que se cruzan este año.",
    riv_puesto:"En la tabla va", riv_ult:"La última vez te ganó.", riv_ult_yo:"La última vez le ganaste.",
    riv_ult_e:"La última vez empataron.", riv_nuevo:"Todavía no jugó esta temporada.", riv_otra:"Juega en otro torneo: no comparten tabla.",
    cal_prog:"Temporada", cal_de:"de", cal_sig:"Lo que viene",
    fed_escalera:"Escalera del poder", fed_anfp:"Asociación local", fed_conmebol:"CONMEBOL", fed_fifa:"FIFA",
    fed_falta:"Te faltan jugadas de poder pa el próximo escalón",
    fed_ok:"Escalón conquistado", fed_guerra:"Guerra de asociaciones",
    fed_cupos:"Cupos internacionales", fed_robado:"Cupo robado a la vecina",
    fed_sin:"Todavía no dirigís la asociación. Gana la elección pa abrir la escalera.",
    fed_subiste:"Subiste un escalón en el poder del fútbol",
    jor_saltar:"Saltar a los resultados", jor_tabla:"Cómo quedó la tabla",
    jor_quieta:"La tabla no se movió con esta fecha.", jor_mundo:"Mientras tanto, afuera",
    jor_tabla_ver:"Ver la tabla completa", jor_esc:"Al escritorio",
    jor_panel:"La liga se movió", jor_ver:"Ver cómo se jugó la fecha",
    jor_cal:"Ir al calendario", jor_repetir:"Repetir la fecha",
    sem_tit:"Parte de la semana", sem_caja:"Caja de la semana", sem_otros:"Otros partidos de la fecha",
    av_jugar:"Jugar", av_semana:"Avanzar semana", av_cierre:"Cerrar temporada",
    q92_calma:"Bajar el perfil", q92_confianza:"Salir con confianza", q92_palo:"Un palo y a la cancha",
    q92_humilde:"Bajar el perfil", q92_bancar:"Bancarlo de frente", q92_palo2:"Un palo y a la siguiente",
    mv_tit:"El mundo se movió", mv_nada:"Semana tranquila afuera. Nadie se movió.",
    mv_dt:"Cambio de banca", mv_fichaje:"Se movió el mercado", mv_racha:"Racha", mv_ver:"Ver todo lo que pasó",
    mv_golpe:"Golpe de la fecha",
    sim_tit:"Simulando temporadas",
    sim_txt:"El club sigue, no se trabó.",
    sim_prog:"Temporada ",
    sim_de:" de ",
    sim_ok:"No se trabó; el juego sigue.",
    sim_cancel:"Cancelar y volver al año de origen",
    sim_ayuda:"Pa probar el juego a fondo: simulo temporadas enteras. Veí el año en pantalla; no se traba. Si cancelai, volvemos al año de origen — la próxima corrida sale distinta.",
    sim_conf5:"Voy a simular 5 temporadas. Vai a ver el progreso; si cancelai, volvemos al año de origen. ¿Seguimos?",
    sim_conf40:"Voy a simular hasta 40 temporadas. No se traba. Cancelar te devuelve al año de origen; la próxima corrida no sale igual. ¿Seguimos?",
    sim_backhint:"Si cancelai, volvemos al año de origen.",
    sim_back:"Volviste a ",
    sim_back2:". Esta corrida no quedó: la próxima va a ser distinta.",
    sim_fecha:"fecha",
    sim_pos:"posición",
    sim_ultcamp:"último campeón",
    sim_campeonar:"campeón",
    cop_viene:"Cruces que vienen en el país",
    cop_resto_grupo:"Resto del grupo",
    cop_sorteo_pendiente:"Los grupos del país ya terminaron su fase. La fase eliminatoria del resto del país no está modelada; seguí las tablas de arriba.",
    cal_prox:"Próximo compromiso",
    cal_ir:"Ir al partido, po",
    cal_sinprox:"No quedan más partidos este año.",
    pla_once:"Once probable",
    pla_form:"Formación",
    pla_pizarra_hint:"La pizarra la armái en la previa del partido.",
    pla_ir_pizarra:"Ir a la previa / pizarra",
    pla_sinpart:"No hay partido pa' armar la pizarra.",
    merc_siempre:"La ventana abre en enero-febrero y junio-julio. Fuera de eso negociái y dejái el trato hecho.",
    merc_lluvia:"Ventana abierta",
    merc_quieto:"Ventana cerrada",
    merc_ventana:"La ventana abre en enero-febrero y junio-julio. Fuera de eso negociái y dejái el trato hecho; firmái cuando el mercado lo permita.",
    merc_cerrada:"Ventana cerrada · próxima: ",
    merc_pre:"Preacuerdos",
    merc_obj_lluvia:"Ventana abierta: cierra ahora si te convence.",
    merc_obj_quieto:"Ventana cerrada: podí negociar y dejar el trato hecho.",
    merc_obj_abierta:"Ventana abierta: cierra ahora si te convence. Son jugadores de los otros clubes, no inventados.",
    merc_obj_cerrada:"Ventana cerrada: podí negociar y dejar el trato hecho."
  },
  /* --- PORTUGUÊS (arranque; el usuario/Grok lo afinan). --- */
  pt:{
    ini_headline:"Você não dirige um time. Dirige uma instituição.",
    ini_bajada:"Gente puxando para lados diferentes, dinheiro que acaba, regras internas que você pode mudar se tiver poder para isso, e uma história real que dá para seguir ou quebrar.",
    ini_elige:"1 · Escolha o clube",
    ini_buscar:"Buscar clube ou cidade…",
    ini_f_todos:"Todos",
    ini_f_clasicos:"Clássicos '91",
    ini_amigo_tit:"… ou jogue contra um amigo",
    ini_amigo_txt:"Um duelo ao vivo, sem contas nem servidor: conectam-se com um código e cada um comanda seu clube.",
    ini_amigo_btn:"🎮 Duelo com um amigo",
    aj_idioma:"Idioma",
    aj_idioma_txt:"Muda o registro dos textos do jogo. O que ainda não estiver traduzido aparece em espanhol neutro.",
    aj_nav:"Navegação",
    aj_nav_pc:"No computador",
    aj_nav_cel:"No celular",
    aj_nav_cinta:"Fita (todas as seções)",
    aj_nav_mas:"Compacto (4 + Mais)",
    aj_nav_txt:"Computador: barra à esquerda ou abas em cima. Celular: a fita de baixo desliza com o dedo. O compacto deixa quatro atalhos e um Mais. Ajustes fica no ⚙️.",
    esc_atiende:"Resolva isto antes de avançar",
    esc_atiende_txt:"Há coisas para resolver antes de apertar Avançar. Toque uma para ir até ela:",
    esc_metas:"O que se espera de você",
    esc_metas_txt:"Metas da diretoria para este ano. Avaliam-se no encerramento.",
    esc_como:"Como",
    esc_ayudante:"Assistente",
    esc_ayudante_txt:"Sua mão direita, de graça e sem servidor. Pergunte de verdade: rival, dinheiro, meta, copa, torcida.",
    esc_decs:"Decisões na mesa",
    esc_semana:"O que aconteceu nesta semana",
    inst_poder:"Jogadas de poder",
    inst_poder_txt:"Não é apertar um botão. Primeiro o grupo tem que estar do seu lado, e você precisa de capital. Cada uma, uma vez por ano.",
    inst_grupos:"Grupos de interesse",
    merc_obj:"Objetivos no mercado",
    merc_ces:"Empréstimos",
    cal_pais:"O país se simula mesmo que você não jogue",
    chip_informe:"Informe da semana",
    chip_rival:"Como vem o rival?",
    chip_plata:"Como está o dinheiro?",
    chip_camarin:"E o vestiário?",
    chip_meta:"O que faço com a meta?",
    chip_domingo:"E no domingo?",
    chip_vende:"Vendemos alguém?",
    chip_capitan:"Falo com o capitão?",
    chip_directorio:"E a diretoria?",
    arco_gol:"⚽ GOL",
    arco_ataja:"🧤 DEFESA",
    arco_barrera:"🧱 A BARREIRA",
    arco_palo:"🪵 TRAVE",
    arco_palo_in:"⚽ TRAVE PRA DENTRO",
    arco_afuera:"↑ PRA FORA",
    arco_defensa:"🛡️ AFASTA",
    arco_hud_pen:"PÊNALTI",
    arco_hud_tl:"FALTA",
    arco_hud_cor:"ESCANTEIO",
    arco_pen_tit:"Pênalti · desenhe o chute",
    arco_tl_tit:"Falta · desenhe o chute",
    arco_cor_tit:"Escanteio · desenhe o cruzamento",
    arco_colocado:"Colocado",
    arco_potente:"Forte",
    arco_picadita:"Cavadinha",
    arco_apunta:"Toque no gol para mirar",
    tanda_tit:"Disputa de pênaltis · desenhe o chute",
    hist_hoy:"O clube hoje",
    esc_once_ver:"Provável escalação de ",
    scout_rival:"Rival", scout_pos:"Pos", scout_nivel:"Nível",
    scout_real:"jogador real documentado",
    scout_estim:"É uma leitura estimada: a escalação final pode mudar.",
    scout_niebla:"Você vê os conhecidos; o resto é névoa. Peça o relatório — não custa caixa.",
    scout_btn:"Relatório completo", scout_sincaja:"O caixa não cobre o relatório",
    scout_comprado:"Relatório pronto", scout_listo:"Relatório pronto", scout_precio:"grátis", scout_gratis:"grátis",
    don_aviso_btn:"Ver um anúncio · apoiar sem dinheiro",
    don_aviso_tit:"Seis segundos do seu tempo",
    don_aviso_txt:"Um dia aqui pode sair um anúncio. Hoje é uma pausa de 6 segundos: o autor não cobra e o jogo não trava. Ninguém te obriga.",
    don_aviso_wait:"Espere um momento…",
    don_aviso_ok:"Pronto. Obrigado pelo tempo.",
    don_aviso_n:"Anúncios vistos nesta partida",
    don_aviso_hint:"Apoiar de graça: você dá atenção, não dinheiro.",
    don_aviso_aj:"O anúncio grátis fica em Ajustes · ⚙️. Ninguém te obriga.",
    dec_urg:"tem que ser resolvida antes da próxima partida",
    ay_once:"Montar a escalação", ay_moral:"Reconquistar o vestiário", ay_plantel:"Ver o elenco",
    ay_finanzas:"Ir a Finanças", ay_inst:"Ir à Diretoria", ay_metas:"Ver as metas",
    ay_previa:"Ver a prévia", ay_mercado:"Ir ao Mercado",
    ay_les:"Lesionados", ay_sinles:"Sem lesionados de peso agora.",
    ay_nopillo:"Não peguei bem. É da escalação, do dinheiro, da meta ou do rival?",
    ay_c_once:"a escalação", ay_c_plata:"o dinheiro", ay_c_meta:"a meta", ay_c_rival:"o rival", ay_c_cam:"o vestiário", ay_c_les:"os lesionados",
    ay_ph:"Pergunte ao auxiliar… (rival, escalação, dinheiro, elenco, meta, mercado…)", ay_preguntar:"Perguntar",
    meta_ir:"Toque para trabalhar esta meta", meta_porque:"Por que importa",
    meta_ok:"Meta cumprida. A diretoria aprova.", meta_pregunta:"O que faço com a meta",
    dec_elige:"Ele escolheria esta", dec_elige_ya:"O auxiliar já marcou a escolha", dec_elige_txt:"O auxiliar se arriscaria aqui. Você decide.", dec_elige_badge:"escolha dele",
    dec_g_partido:"⚽ Partida", dec_g_plata:"💰 Dinheiro", dec_g_inst:"🏛️ Diretoria",
    jor_tit:"A rodada rola", jor_resto:"Enquanto isso, nos outros campos:",
    mas_cuenta:"Conta", mep_solo:"Nesta época só se acompanha o torneio local: o resto do continente não está modelado para este ano.",
    mep_nacional:"o Nacional",
    riv_racha:"Como vem", riv_sin:"Primeira vez que se enfrentam este ano.",
    riv_puesto:"Na tabela está", riv_ult:"Da última vez eles ganharam.", riv_ult_yo:"Da última vez você ganhou.",
    riv_ult_e:"Da última vez empataram.", riv_nuevo:"Ainda não jogou nesta temporada.", riv_otra:"Joga em outro torneio: não compartilham tabela.",
    cal_prog:"Temporada", cal_de:"de", cal_sig:"O que vem",
    fed_escalera:"Escada do poder", fed_anfp:"Associação local", fed_conmebol:"CONMEBOL", fed_fifa:"FIFA",
    fed_falta:"Faltam jogadas de poder para o próximo degrau",
    fed_ok:"Degrau conquistado", fed_guerra:"Guerra de associações",
    fed_cupos:"Vagas internacionais", fed_robado:"Vaga roubada da vizinha",
    fed_sin:"Você ainda não dirige a associação. Ganhe a eleição para abrir a escada.",
    fed_subiste:"Você subiu um degrau no poder do futebol",
    jor_saltar:"Pular para os resultados", jor_tabla:"Como ficou a tabela",
    jor_quieta:"A tabela não mudou nesta rodada.", jor_mundo:"Enquanto isso, lá fora",
    jor_tabla_ver:"Ver a tabela completa", jor_esc:"Para a mesa",
    jor_panel:"A liga se mexeu", jor_ver:"Ver como foi a rodada",
    jor_cal:"Ir ao calendário", jor_repetir:"Repetir a rodada",
    sem_tit:"Boletim da semana", sem_caja:"Caixa da semana", sem_otros:"Outras partidas da rodada",
    av_jugar:"Jogar", av_semana:"Avançar semana", av_cierre:"Encerrar temporada",
    q92_calma:"Baixar a bola", q92_confianza:"Sair com confiança", q92_palo:"Uma alfinetada e para o campo",
    q92_humilde:"Baixar a bola", q92_bancar:"Bancar de frente", q92_palo2:"Uma alfinetada e bola para frente",
    mv_tit:"O mundo se mexeu", mv_nada:"Semana calma lá fora. Ninguém se mexeu.",
    mv_dt:"Troca de comando", mv_fichaje:"O mercado se mexeu", mv_racha:"Sequência", mv_ver:"Ver tudo o que rolou",
    mv_golpe:"Zebra da rodada",
    hold_tit:"Partida em pausa",
    hold_txt:"As decisões continuam aí. Volte ao jogo quando quiser.",
    hold_btn:"Voltar à partida",
    hold_avanza:"Há uma partida em curso. Volte para terminá-la.",
    sim_tit:"Simulando temporadas",
    sim_txt:"O clube segue, não travou.",
    sim_prog:"Temporada ",
    sim_de:" de ",
    sim_ok:"Não travou; o jogo segue.",
    sim_cancel:"Cancelar e voltar ao ano de origem",
    sim_ayuda:"Para testar o jogo: simulo temporadas inteiras. Você vê o ano na tela; não trava. Se cancelar, voltamos ao ano de origem — a próxima corrida sai diferente.",
    sim_conf5:"Vou simular 5 temporadas. Você vê o progresso; se cancelar, voltamos ao ano de origem. Seguir?",
    sim_conf40:"Vou simular até 40 temporadas. Não trava. Cancelar te devolve ao ano de origem; a próxima corrida não sai igual. Seguir?",
    sim_backhint:"Se cancelar, voltamos ao ano de origem.",
    sim_back:"Você voltou a ",
    sim_back2:". Esta corrida não ficou: a próxima vai ser diferente.",
    sim_fecha:"rodada",
    sim_pos:"posição",
    sim_ultcamp:"último campeão",
    sim_campeonar:"campeão",
    cop_viene:"Cruzamentos que vêm por aí no país",
    cop_resto_grupo:"Resto do grupo",
    cop_sorteo_pendiente:"Os grupos do país já terminaram sua fase. A fase eliminatória do resto do país não está modelada; siga as tabelas acima.",
    cal_prox:"Próximo compromisso",
    cal_ir:"Ir à partida",
    cal_sinprox:"Não há mais partidas este ano.",
    pla_once:"Onze provável",
    pla_form:"Formação",
    pla_pizarra_hint:"O quadro tático se arma na prévia da partida.",
    pla_ir_pizarra:"Ir à prévia / quadro",
    pla_sinpart:"Não há partida para armar o quadro.",
    merc_siempre:"A janela abre em janeiro-fevereiro e junho-julho. Fora disso você negocia e deixa o trato feito.",
    merc_lluvia:"Janela aberta",
    merc_quieto:"Janela fechada",
    merc_ventana:"A janela abre em janeiro-fevereiro e junho-julho. Fora disso você negocia e deixa o trato feito; assina quando o mercado permitir.",
    merc_cerrada:"Janela fechada · próxima: ",
    merc_pre:"Pré-acordos",
    merc_obj_lluvia:"Janela aberta: feche agora se convencer.",
    merc_obj_quieto:"Janela fechada: você pode negociar e deixar o trato feito.",
    merc_obj_abierta:"Janela aberta: feche agora se convencer. São jogadores dos outros clubes, não inventados.",
    merc_obj_cerrada:"Janela fechada: você pode negociar e deixar o trato feito."
  },
  en:{
    ini_headline:"You don't run a team. You run an institution.",
    ini_bajada:"People pulling in different directions, money that runs out, house rules you can change if you have the power, and a real history you can follow or break.",
    ini_elige:"1 · Pick a club",
    ini_buscar:"Search club or city…",
    ini_f_todos:"All",
    ini_f_clasicos:"'91 classics",
    ini_amigo_tit:"… or play a friend",
    ini_amigo_txt:"A live directed duel, no accounts, no server: you connect with a code and each of you runs a club.",
    ini_amigo_btn:"🎮 Duel a friend",
    aj_idioma:"Language",
    aj_idioma_txt:"Changes the game's voice. Anything not translated yet falls back to neutral Spanish.",
    aj_nav:"Navigation",
    aj_nav_pc:"On the computer",
    aj_nav_cel:"On the phone",
    aj_nav_cinta:"Ribbon (every section)",
    aj_nav_mas:"Compact (4 + More)",
    aj_nav_txt:"Computer: left bar (Wii-style) or tabs on top. Phone: swipe the bottom ribbon. Compact keeps four shortcuts plus More. Settings always lives on ⚙️.",
    esc_atiende:"Handle this before you advance",
    esc_atiende_txt:"There are things to settle before you hit Advance. Tap one to go deal with it:",
    esc_metas:"What they expect of you",
    esc_metas_txt:"The board's targets for this year. They get scored at the close.",
    esc_como:"How",
    esc_ayudante:"Assistant",
    esc_ayudante_txt:"Your right hand, free, no server. Ask for real: the rival, the money, the target, the cup, the barra.",
    esc_decs:"Decisions on the table",
    esc_semana:"What happened this week",
    inst_poder:"Power plays",
    inst_poder_txt:"It is not a button. First you need the group on your side, and capital. Each one, once a year.",
    inst_grupos:"Interest groups",
    merc_obj:"Market objectives",
    merc_ces:"Loans",
    cal_pais:"The country simulates even if you don't play it",
    chip_informe:"Week report",
    chip_rival:"How's the rival looking?",
    chip_plata:"How's the money?",
    chip_camarin:"And the dressing room?",
    chip_meta:"What do I do with the target?",
    chip_domingo:"Sunday?",
    chip_vende:"Do we sell someone?",
    chip_capitan:"Do I talk to the captain?",
    chip_directorio:"And the board?",
    arco_gol:"⚽ GOAL",
    arco_ataja:"🧤 SAVED",
    arco_barrera:"🧱 THE WALL",
    arco_palo:"🪵 CROSSBAR",
    arco_palo_in:"⚽ IN OFF THE POST",
    arco_afuera:"↑ WIDE",
    arco_defensa:"🛡️ CLEARED",
    arco_hud_pen:"PENALTY",
    arco_hud_tl:"FREE KICK",
    arco_hud_cor:"CORNER",
    arco_pen_tit:"Penalty · draw your shot",
    arco_tl_tit:"Free kick · draw your shot",
    arco_cor_tit:"Corner · draw the cross",
    arco_colocado:"Placed",
    arco_potente:"Power",
    arco_picadita:"Chip",
    arco_apunta:"Tap the goal to aim",
    tanda_tit:"Shootout · draw your penalty",
    hist_hoy:"The club today",
    esc_once_ver:"Likely XI of ",
    scout_rival:"Rival", scout_pos:"Pos", scout_nivel:"Rating",
    scout_real:"documented real player",
    scout_estim:"It's an estimate: the final lineup may change.",
    scout_niebla:"You see the known faces; the rest is fog. Ask for the report — it costs nothing.",
    scout_btn:"Full report", scout_sincaja:"You can't afford the report",
    scout_comprado:"Report ready", scout_listo:"Report ready", scout_precio:"free", scout_gratis:"free",
    don_aviso_btn:"Watch a spot · support for free",
    don_aviso_tit:"Six seconds of your time",
    don_aviso_txt:"One day a real ad may play here. Today it's a 6-second pause: the author doesn't charge and nothing is locked. Nobody makes you tap it.",
    don_aviso_wait:"Hang on a moment…",
    don_aviso_ok:"Done. Thanks for the time.",
    don_aviso_n:"Spots watched this save",
    don_aviso_hint:"Free support: you give attention, not money.",
    don_aviso_aj:"The free spot lives in Settings · ⚙️. Nobody makes you tap it.",
    dec_urg:"must be settled before the next match",
    ay_once:"Set the lineup", ay_moral:"Win back the dressing room", ay_plantel:"See the squad",
    ay_finanzas:"Go to Finance", ay_inst:"Go to Board", ay_metas:"See the targets",
    ay_previa:"See the preview", ay_mercado:"Go to Market",
    ay_les:"Injured", ay_sinles:"No key injuries right now.",
    ay_nopillo:"I didn't get that. Is it about the lineup, money, the target or the rival?",
    ay_c_once:"the lineup", ay_c_plata:"the money", ay_c_meta:"the target", ay_c_rival:"the rival", ay_c_cam:"the dressing room", ay_c_les:"the injured",
    ay_ph:"Ask the assistant… (rival, lineup, money, squad, target, market…)", ay_preguntar:"Ask",
    meta_ir:"Tap to go work on this target", meta_porque:"Why it matters",
    meta_ok:"Target met. The board signs off.", meta_pregunta:"What do I do about the target",
    dec_elige:"He'd pick this one", dec_elige_ya:"The assistant already marked his pick", dec_elige_txt:"The assistant would go for this. Your call.", dec_elige_badge:"his pick",
    dec_g_partido:"⚽ Match", dec_g_plata:"💰 Money", dec_g_inst:"🏛️ Board",
    jor_tit:"The round is being played", jor_resto:"Meanwhile, on the other pitches:",
    mas_cuenta:"Account", mep_solo:"In this era only the local league is followed: the rest of the continent isn't modelled for this year.",
    mep_nacional:"the national league",
    riv_racha:"Recent form", riv_sin:"First time you meet this year.",
    riv_puesto:"In the table they sit", riv_ult:"They beat you last time.", riv_ult_yo:"You beat them last time.",
    riv_ult_e:"You drew last time.", riv_nuevo:"They haven't played yet this season.", riv_otra:"They play in another competition: no shared table.",
    cal_prog:"Season", cal_de:"of", cal_sig:"What's coming",
    fed_escalera:"Ladder of power", fed_anfp:"Local association", fed_conmebol:"CONMEBOL", fed_fifa:"FIFA",
    fed_falta:"You need more power plays for the next rung",
    fed_ok:"Rung taken", fed_guerra:"War of associations",
    fed_cupos:"International slots", fed_robado:"Slot taken from the neighbour",
    fed_sin:"You don't run the association yet. Win the election to open the ladder.",
    fed_subiste:"You climbed a rung in football's power",
    jor_saltar:"Skip to the results", jor_tabla:"How the table ended up",
    jor_quieta:"The table didn't move this round.", jor_mundo:"Meanwhile, elsewhere",
    jor_tabla_ver:"See the full table", jor_esc:"To the desk",
    jor_panel:"The league moved", jor_ver:"Watch how the round played out",
    jor_cal:"Go to the calendar", jor_repetir:"Replay the round",
    sem_tit:"This week's bulletin", sem_caja:"Week's cash", sem_otros:"Other matches this round",
    av_jugar:"Play", av_semana:"Advance week", av_cierre:"Close the season",
    q92_calma:"Play it down", q92_confianza:"Sound confident", q92_palo:"A jab, then the pitch",
    q92_humilde:"Play it down", q92_bancar:"Back him publicly", q92_palo2:"A jab, then the next one",
    mv_tit:"The world moved", mv_nada:"Quiet week out there. Nobody moved.",
    mv_dt:"Manager change", mv_fichaje:"The market moved", mv_racha:"Streak", mv_ver:"See everything that happened",
    mv_golpe:"Upset of the round",
    hold_tit:"Match paused",
    hold_txt:"Your decisions are still there. Come back to the match when you want.",
    hold_btn:"Back to the match",
    hold_avanza:"There's a match in progress. Go finish it.",
    sim_tit:"Simulating seasons",
    sim_txt:"The club is still going. It didn't freeze.",
    sim_prog:"Season ",
    sim_de:" of ",
    sim_ok:"It didn't freeze; the game is running.",
    sim_cancel:"Cancel and go back to the starting year",
    sim_ayuda:"To stress-test the game I simulate full seasons. You see the year on screen; it doesn't freeze. Cancel restores the year you started from — the next run will be different.",
    sim_conf5:"I'll simulate 5 seasons. You'll see progress; cancel restores the starting year. Continue?",
    sim_conf40:"I'll simulate up to 40 seasons. It won't freeze. Cancel restores the starting year; the next run won't play out the same. Continue?",
    sim_backhint:"If you cancel, we go back to the starting year.",
    sim_back:"You're back in ",
    sim_back2:". This run didn't stick: the next one will be different.",
    sim_fecha:"matchday",
    sim_pos:"position",
    sim_ultcamp:"last champion",
    sim_campeonar:"champion",
    cop_viene:"Upcoming crosses around the country",
    cop_resto_grupo:"Rest of the group",
    cop_sorteo_pendiente:"The country's groups already finished. The rest of the country's knockout stage isn't modeled; follow the tables above.",
    cal_prox:"Next fixture",
    cal_ir:"Go to the match",
    cal_sinprox:"No more matches this year.",
    pla_once:"Probable XI",
    pla_form:"Formation",
    pla_pizarra_hint:"The tactics board is set in the match preview.",
    pla_ir_pizarra:"Go to preview / board",
    pla_sinpart:"No match to set the board.",
    merc_siempre:"The window opens in January–February and June–July. Outside it you negotiate and leave the deal done.",
    merc_lluvia:"Window open",
    merc_quieto:"Window closed",
    merc_ventana:"The window opens in January–February and June–July. Outside it you negotiate and leave the deal done; you sign when the market allows.",
    merc_cerrada:"Window closed · next: ",
    merc_pre:"Pre-agreements",
    merc_obj_lluvia:"Window open: close now if it convinces you.",
    merc_obj_quieto:"Window closed: you can negotiate and leave the deal done.",
    merc_obj_abierta:"Window open: close now if it convinces you. These are real players from other clubs, not made up.",
    merc_obj_cerrada:"Window closed: you can negotiate and leave the deal done."
  }
};

/* ---- Pools de tuits POR IDIOMA (se suman a los del pool base según contexto).
   Chilensis crudo de cancha (aparece SOLO en modo Chilensis; neutro/pt quedan limpios).
   Escrito con la voz del usuario. Placeholder {GOLEADOR}. --- */
var _GOL_CL=[
  {quien:"@barra_del_sur", txt:"GOOOOOOOL GOOOOOL CONCHETUMARE, TE AMO {GOLEADOR}, HAZME UN HIJO!!"},
  {quien:"@weon_del_metro", txt:"GOOOOL WN GOOOOL, {GOLEADOR} ERÍS GRANDE, LA CTM QUE TE AMO"},
  {quien:"@hincha_insomne", txt:"AAAAAH GOOOOOL, {GOLEADOR} POR LA CHUCHA QUE JUEGA BIEN, GRÍTALO"},
  {quien:"@pibe_popular23", txt:"SE ROMPIÓ LA RED CTM, {GOLEADOR} ERÍS UN CRACK, TE LLEVO AL ALTAR"},
  {quien:"@dona_del_barrio", txt:"gooool mijito lindo, {GOLEADOR} me lo saludan a la mamá, qué golazo por dios"}
];
var TUITS_IDIOMA={
  cl:{
    gol_propio:_GOL_CL,
    gana_agonico:_GOL_CL.concat([{quien:"@albo_insomne", txt:"EN LA HORA CTM, {GOLEADOR} NOS SALVÓ LA VIDA, LLORO"}]),
    remontada:_GOL_CL.concat([{quien:"@garrafal_cl", txt:"DE LA NADA WN, {GOLEADOR} DIO VUELTA TODO, QUÉ EQUIPO CTM"}]),
    clasico_gana:_GOL_CL.concat([{quien:"@barra_del_sur", txt:"EN EL CLÁSICO CTM, {GOLEADOR} LOS HIZO LLORAR, ESTO NO SE OLVIDA"}]),
    goleada_favor:_GOL_CL,
    hat_trick:[{quien:"@datofutbol_cl", txt:"TRES {GOLEADOR}, TRES CTM. HÁGANLE UNA ESTATUA AL TIRO"}].concat(_GOL_CL)
  }
};

/* Resuelve una clave por el idioma activo, con fallback a neutro y a un default. */
function T(clave, neutro){
  var pack=FRASES[IDIOMA];
  if(pack && pack[clave]!=null) return pack[clave];
  if(FRASES.neutro && FRASES.neutro[clave]!=null) return FRASES.neutro[clave];
  return (neutro!=null)?neutro:clave;
}
/* Cambia el idioma activo (si existe el pack). */
function setIdioma(k){ if(k && (FRASES[k]||k==="neutro")) IDIOMA=k; return IDIOMA; }
function idiomaActual(){ return IDIOMA; }
